"""add configurable ERP foundation

Revision ID: c4d5e6f7g8h9
Revises: b7c8d9e0f1a2
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "c4d5e6f7g8h9"
down_revision: Union[str, Sequence[str], None] = "b7c8d9e0f1a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    json = postgresql.JSONB(astext_type=sa.Text())
    op.create_table("erp_access_roles",
        sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("description", sa.Text()),
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("organization_id", "code", name="uq_erp_access_roles_org_code"))
    op.create_table("erp_capabilities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("access_role_id", sa.Integer(), sa.ForeignKey("erp_access_roles.id", ondelete="CASCADE"), nullable=False), sa.Column("resource", sa.String(80), nullable=False), sa.Column("action", sa.String(24), nullable=False), sa.UniqueConstraint("access_role_id", "resource", "action", name="uq_erp_capability"))
    op.create_table("erp_account_roles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("account_id", sa.Integer(), sa.ForeignKey("user_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("access_role_id", sa.Integer(), sa.ForeignKey("erp_access_roles.id", ondelete="CASCADE"), nullable=False), sa.Column("scope", json, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("account_id", "access_role_id", name="uq_erp_account_role"))
    op.create_table("erp_custom_fields", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("resource", sa.String(80), nullable=False), sa.Column("key", sa.String(64), nullable=False), sa.Column("label", sa.Text(), nullable=False), sa.Column("field_type", sa.String(24), nullable=False), sa.Column("options", json, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("required", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("posting_relevant", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.UniqueConstraint("organization_id", "resource", "key", name="uq_erp_custom_field"))
    op.create_table("erp_sequences", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("key", sa.String(80), nullable=False), sa.Column("prefix", sa.String(40), nullable=False, server_default=""), sa.Column("next_number", sa.Integer(), nullable=False, server_default="1"), sa.Column("padding", sa.Integer(), nullable=False, server_default="5"), sa.UniqueConstraint("organization_id", "key", name="uq_erp_sequence"))
    op.create_table("erp_parties", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("public_id", postgresql.UUID(as_uuid=True), nullable=False, unique=True, server_default=sa.text("gen_random_uuid()")), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("legacy_client_id", sa.Integer(), sa.ForeignKey("clients.id", ondelete="SET NULL"), unique=True), sa.Column("party_type", sa.String(24), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("email", sa.Text()), sa.Column("phone", sa.Text()), sa.Column("tax_id", sa.Text()), sa.Column("credit_limit", sa.Numeric(18, 4)), sa.Column("currency", sa.String(3), nullable=False, server_default="MNT"), sa.Column("status", sa.String(24), nullable=False, server_default="active"), sa.Column("contacts", json, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("addresses", json, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("custom", json, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "code", name="uq_erp_party_org_code"))
    op.create_index("ix_erp_parties_org_type", "erp_parties", ["organization_id", "party_type"])
    op.create_table("erp_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("public_id", postgresql.UUID(as_uuid=True), nullable=False, unique=True, server_default=sa.text("gen_random_uuid()")), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("item_type", sa.String(24), nullable=False, server_default="product"), sa.Column("item_group", sa.Text()), sa.Column("unit", sa.String(24), nullable=False, server_default="Nos"), sa.Column("valuation_method", sa.String(24), nullable=False, server_default="moving_average"), sa.Column("standard_cost", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("reorder_level", sa.Numeric(18, 4)), sa.Column("is_stock_item", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("custom", json, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "code", name="uq_erp_item_org_code"))
    op.create_table("erp_warehouses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("parent_id", sa.Integer(), sa.ForeignKey("erp_warehouses.id", ondelete="SET NULL")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.UniqueConstraint("organization_id", "code", name="uq_erp_warehouse_org_code"))
    op.create_table("erp_accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("parent_id", sa.Integer(), sa.ForeignKey("erp_accounts.id", ondelete="SET NULL")), sa.Column("code", sa.String(64), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("account_type", sa.String(32), nullable=False), sa.Column("is_group", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.UniqueConstraint("organization_id", "code", name="uq_erp_account_org_code"))
    op.create_table("erp_documents", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("public_id", postgresql.UUID(as_uuid=True), nullable=False, unique=True, server_default=sa.text("gen_random_uuid()")), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("document_type", sa.String(64), nullable=False), sa.Column("number", sa.String(80), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="draft"), sa.Column("party_id", sa.Integer(), sa.ForeignKey("erp_parties.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("source_document_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="SET NULL")), sa.Column("amended_from_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="SET NULL")), sa.Column("currency", sa.String(3), nullable=False, server_default="MNT"), sa.Column("exchange_rate", sa.Numeric(24, 10), nullable=False, server_default="1"), sa.Column("posting_date", sa.Date(), nullable=False, server_default=sa.func.current_date()), sa.Column("due_date", sa.Date()), sa.Column("net_total", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("tax_total", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("grand_total", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("outstanding_amount", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("payload", json, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("custom", json, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("submitted_by_account_id", sa.Integer(), sa.ForeignKey("user_accounts.id", ondelete="SET NULL")), sa.Column("cancelled_at", sa.DateTime(timezone=True)), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "document_type", "number", name="uq_erp_document_number"))
    op.create_index("ix_erp_documents_org_type_status", "erp_documents", ["organization_id", "document_type", "status"])
    op.create_index("ix_erp_documents_party", "erp_documents", ["organization_id", "party_id", "posting_date"])
    op.create_table("erp_document_lines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("item_id", sa.Integer(), sa.ForeignKey("erp_items.id", ondelete="SET NULL")), sa.Column("warehouse_id", sa.Integer(), sa.ForeignKey("erp_warehouses.id", ondelete="SET NULL")), sa.Column("account_id", sa.Integer(), sa.ForeignKey("erp_accounts.id", ondelete="SET NULL")), sa.Column("description", sa.Text(), nullable=False), sa.Column("quantity", sa.Numeric(18, 6), nullable=False, server_default="1"), sa.Column("rate", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("amount", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("tax_rate", sa.Numeric(9, 4), nullable=False, server_default="0"), sa.Column("tax_amount", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("position", sa.Integer(), nullable=False, server_default="0"), sa.Column("data", json, nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.create_index("ix_erp_document_lines_document", "erp_document_lines", ["document_id", "position"])
    op.create_table("erp_general_ledger_entries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("document_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="RESTRICT"), nullable=False), sa.Column("account_id", sa.Integer(), sa.ForeignKey("erp_accounts.id", ondelete="RESTRICT"), nullable=False), sa.Column("party_id", sa.Integer(), sa.ForeignKey("erp_parties.id", ondelete="SET NULL")), sa.Column("posting_date", sa.Date(), nullable=False), sa.Column("debit", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("credit", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("memo", sa.Text()), sa.Column("reversal_of_id", sa.Integer(), sa.ForeignKey("erp_general_ledger_entries.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index("ix_erp_gl_org_account_date", "erp_general_ledger_entries", ["organization_id", "account_id", "posting_date"])
    op.create_table("erp_stock_ledger_entries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("document_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="RESTRICT"), nullable=False), sa.Column("item_id", sa.Integer(), sa.ForeignKey("erp_items.id", ondelete="RESTRICT"), nullable=False), sa.Column("warehouse_id", sa.Integer(), sa.ForeignKey("erp_warehouses.id", ondelete="RESTRICT"), nullable=False), sa.Column("posting_date", sa.Date(), nullable=False), sa.Column("quantity_delta", sa.Numeric(18, 6), nullable=False), sa.Column("value_delta", sa.Numeric(18, 4), nullable=False), sa.Column("valuation_rate", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index("ix_erp_stock_org_item_warehouse_date", "erp_stock_ledger_entries", ["organization_id", "item_id", "warehouse_id", "posting_date"])
    op.create_table("erp_posting_periods", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(80), nullable=False), sa.Column("starts_on", sa.Date(), nullable=False), sa.Column("ends_on", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="open"), sa.Column("closed_by_account_id", sa.Integer(), sa.ForeignKey("user_accounts.id", ondelete="SET NULL")), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "name", name="uq_erp_posting_period_name"))
    op.create_index("ix_erp_posting_period_dates", "erp_posting_periods", ["organization_id", "starts_on", "ends_on"])
    op.create_table("erp_approval_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("resource", sa.String(80), nullable=False), sa.Column("minimum_amount", sa.Numeric(18, 4), nullable=False, server_default="0"), sa.Column("required_access_role_id", sa.Integer(), sa.ForeignKey("erp_access_roles.id", ondelete="SET NULL")), sa.Column("priority", sa.Integer(), nullable=False, server_default="100"), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "resource", "priority", name="uq_erp_approval_rule_priority"))
    op.create_table("erp_payment_allocations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("payment_document_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("invoice_document_id", sa.Integer(), sa.ForeignKey("erp_documents.id", ondelete="RESTRICT"), nullable=False), sa.Column("amount", sa.Numeric(18, 4), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.UniqueConstraint("payment_document_id", "invoice_document_id", name="uq_erp_payment_allocation"))
    op.create_table("erp_import_batches", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("created_by_account_id", sa.Integer(), sa.ForeignKey("user_accounts.id", ondelete="SET NULL")), sa.Column("entity", sa.String(40), nullable=False), sa.Column("source_format", sa.String(32), nullable=False, server_default="generic"), sa.Column("state", sa.String(24), nullable=False, server_default="draft"), sa.Column("rows", json, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("validation_errors", json, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("committed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index("ix_erp_import_batches_org_state", "erp_import_batches", ["organization_id", "state", "created_at"])
    # Existing project clients become ERP customers without changing legacy APIs.
    op.execute("""INSERT INTO erp_parties (organization_id, legacy_client_id, party_type, code, name, currency, contacts, addresses, custom)
        SELECT organization_id, id, 'customer', code, name, default_currency, contacts, '[]'::jsonb, '{}'::jsonb FROM clients
        ON CONFLICT (legacy_client_id) DO NOTHING""")


def downgrade() -> None:
    for table in ("erp_import_batches", "erp_payment_allocations", "erp_approval_rules", "erp_posting_periods", "erp_stock_ledger_entries", "erp_general_ledger_entries", "erp_document_lines", "erp_documents", "erp_accounts", "erp_warehouses", "erp_items", "erp_parties", "erp_sequences", "erp_custom_fields", "erp_account_roles", "erp_capabilities", "erp_access_roles"):
        op.drop_table(table)
