import { useMemo, useState } from 'react'
import { CalendarDays, Plus } from 'lucide-react'
import { useCalendarEvents, useCreateCalendarEntry, useCreateEnterpriseTask, useHolidaySettings, useSetHolidayCountry } from '../api/enterprise'
import { EMPTY_ROLES, useAuthStore } from '../store/auth'

function localDate(value: Date) { const offset = value.getTimezoneOffset() * 60_000; return new Date(value.getTime() - offset).toISOString().slice(0, 10) }

export function CalendarWorkspacePage() {
  const [scope, setScope] = useState<'private' | 'corporate'>('private')
  const [anchor, setAnchor] = useState(() => new Date())
  const [creating, setCreating] = useState(false)
  const [kind, setKind] = useState<'task' | 'reminder' | 'event'>('reminder')
  const [form, setForm] = useState({ title: '', description: '', starts_at: '', ends_at: '', visibility: 'private' })
  const roles = useAuthStore((state) => state.actor?.roles ?? EMPTY_ROLES)
  const canPublish = roles.some((role) => ['admin', 'manager', 'team_lead'].includes(role))
  const isAdmin = roles.includes('admin')
  const days = useMemo(() => { const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); first.setDate(first.getDate() - ((first.getDay() + 6) % 7)); return Array.from({ length: 42 }, (_, index) => { const day = new Date(first); day.setDate(day.getDate() + index); return day }) }, [anchor])
  const period = { date_from: localDate(days[0]), date_to: localDate(days[41]) }
  const events = useCalendarEvents(scope, period)
  const holidaySettings = useHolidaySettings(); const setCountry = useSetHolidayCountry()
  const createEntry = useCreateCalendarEntry(); const createTask = useCreateEnterpriseTask()
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const starts_at = new Date(form.starts_at).toISOString(); const ends_at = new Date(form.ends_at).toISOString(); if (kind === 'task') await createTask.mutateAsync({ title: form.title, description: form.description || null, start_at: starts_at, deadline_at: ends_at, workflow_status: 'to_do' }); else await createEntry.mutateAsync({ kind, visibility: form.visibility, title: form.title, description: form.description || null, starts_at, ends_at, remind_at: kind === 'reminder' ? starts_at : null }); setForm({ title: '', description: '', starts_at: '', ends_at: '', visibility: 'private' }); setCreating(false) }
  const all = [...(events.data?.tasks ?? []), ...(events.data?.entries ?? []), ...(events.data?.holidays ?? []), ...(events.data?.time_blocks ?? [])]
  const holidayKeys = new Set((events.data?.holidays ?? []).filter((item: any) => item.kind === 'holiday').map((item: any) => item.starts_at?.slice(0, 10)))
  const todayKey = localDate(new Date())
  return <div className="calendar-workspace"><div className="view-toolbar"><div><h2>Календарь</h2><p>Даалгавар, сануулга, үйл явдал болон компанийн чухал өдрүүд.</p></div><div className="toolbar-cluster"><div className="segmented-control"><button className={scope === 'private' ? 'active' : ''} onClick={() => setScope('private')}>Хувийн</button><button className={scope === 'corporate' ? 'active' : ''} onClick={() => setScope('corporate')}>Компанийн</button></div><button className="primary-action compact" onClick={() => { setForm({ ...form, visibility: scope === 'corporate' && canPublish ? 'company' : 'private' }); setCreating(true) }}><Plus size={16} />Үүсгэх</button></div></div>
    <div className="calendar-month-nav"><strong>{anchor.toLocaleDateString('mn-MN', { year: 'numeric', month: 'long' })}</strong><div className="calendar-holiday-setting"><span className="holiday-country">Амралт: {holidaySettings.data?.country || 'MN'}</span>{isAdmin && <select aria-label="Амралтын өдрийн улс" value={holidaySettings.data?.country || 'MN'} onChange={(event) => setCountry.mutate(event.target.value)} disabled={setCountry.isPending}>{holidaySettings.data?.countries.map((country) => <option key={country.countryCode} value={country.countryCode}>{country.name}</option>)}</select>}</div><div className="calendar-nav-actions"><button onClick={() => setAnchor(new Date(anchor.getFullYear(), anchor.getMonth() - 1, 1))} aria-label="Өмнөх сар">←</button><button onClick={() => setAnchor(new Date(anchor.getFullYear(), anchor.getMonth() + 1, 1))} aria-label="Дараагийн сар">→</button></div></div>
    <div className="planning-calendar panel">{days.map((day) => { const key = localDate(day); const items = all.filter((item: any) => (item.starts_at || item.deadline_at)?.slice(0, 10) === key); const redDay = day.getDay() === 0 || day.getDay() === 6 || holidayKeys.has(key); return <section key={key} className={`${day.getMonth() === anchor.getMonth() ? '' : 'outside'} ${redDay ? 'red-day' : ''} ${key === todayKey ? 'today' : ''}`}><header><strong>{day.getDate()}</strong><span>{day.toLocaleDateString('mn-MN', { weekday: 'short' })}</span></header>{items.map((item: any) => <article className={`calendar-item ${item.kind}`} key={`${item.kind}-${item.id}`}><strong>{item.title}</strong><small>{item.kind === 'task' ? item.primary_owner_name || 'Даалгавар' : item.kind === 'holiday' ? 'Нийтийн амралт' : item.kind === 'birthday' ? 'Төрсөн өдөр' : item.visibility === 'company' ? 'Компанийн үйл явдал' : item.kind === 'reminder' ? 'Сануулга' : 'Хувийн үйл явдал'}</small></article>)}</section> })}</div>
    {creating && <div className="sheet-backdrop" onMouseDown={() => setCreating(false)}><aside className="detail-sheet" onMouseDown={(event) => event.stopPropagation()}><div className="sheet-header"><div><span className="eyebrow">Calendar item</span><h2>Шинэ зүйл үүсгэх</h2></div><CalendarDays /></div><form className="sheet-form" onSubmit={submit}><label>Төрөл<select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="task">Даалгавар</option><option value="reminder">Сануулга</option><option value="event">Үйл явдал</option></select></label>{kind !== 'task' && canPublish && <label>Харагдац<select value={form.visibility} onChange={(event) => setForm({ ...form, visibility: event.target.value })}><option value="private">Хувийн</option><option value="company">Компанийн</option></select></label>}<label>Гарчиг<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Тайлбар<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Эхлэх<input required type="datetime-local" value={form.starts_at} onChange={(event) => setForm({ ...form, starts_at: event.target.value })} /></label><label>Дуусах<input required type="datetime-local" value={form.ends_at} onChange={(event) => setForm({ ...form, ends_at: event.target.value })} /></label><button className="primary-action" disabled={createEntry.isPending || createTask.isPending}>Хадгалах</button></form></aside></div>}
  </div>
}
