import { useMemo, useState } from 'react'
import { CalendarDays, Plus, Trash2 } from 'lucide-react'
import { useCalendarEvents, useCreateTimeBlock, useDeleteTimeBlock, useUpdateEnterpriseTask } from '../api/enterprise'

function localDate(value: Date) { const offset = value.getTimezoneOffset() * 60_000; return new Date(value.getTime() - offset).toISOString().slice(0, 10) }

export function CalendarWorkspacePage() {
  const [scope, setScope] = useState<'private' | 'corporate'>('private')
  const [anchor, setAnchor] = useState(() => new Date())
  const [creating, setCreating] = useState(false)
  const [form, setForm] = useState({ title: '', starts_at: '', ends_at: '' })
  const days = useMemo(() => { const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); first.setDate(first.getDate() - ((first.getDay() + 6) % 7)); return Array.from({ length: 42 }, (_, index) => { const day = new Date(first); day.setDate(day.getDate() + index); return day }) }, [anchor])
  const period = { date_from: localDate(days[0]), date_to: localDate(days[41]) }
  const events = useCalendarEvents(scope, period)
  const createBlock = useCreateTimeBlock()
  const deleteBlock = useDeleteTimeBlock()
  const updateTask = useUpdateEnterpriseTask()
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await createBlock.mutateAsync({ title: form.title, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString() }); setForm({ title: '', starts_at: '', ends_at: '' }); setCreating(false) }
  const rescheduleTask = async (task: any, field: 'start_at' | 'deadline_at', value: string) => { await updateTask.mutateAsync({ id: task.id, version: task.version, [field]: value ? new Date(value).toISOString() : null }) }
  return <div className="calendar-workspace"><div className="view-toolbar"><div><h2>Календарь</h2><p>Даалгавар болон хувийн ажлын цагаа нэг дор төлөвлөнө.</p></div><div className="toolbar-cluster"><div className="segmented-control"><button className={scope === 'private' ? 'active' : ''} onClick={() => setScope('private')}>Хувийн</button><button className={scope === 'corporate' ? 'active' : ''} onClick={() => setScope('corporate')}>Компанийн</button></div>{scope === 'private' && <button className="primary-action compact" onClick={() => setCreating(true)}><Plus size={16} />Цаг төлөвлөх</button>}</div></div>
    <div className="calendar-month-nav"><button onClick={() => setAnchor(new Date(anchor.getFullYear(), anchor.getMonth() - 1, 1))}>←</button><strong>{anchor.toLocaleDateString('mn-MN', { year: 'numeric', month: 'long' })}</strong><button onClick={() => setAnchor(new Date(anchor.getFullYear(), anchor.getMonth() + 1, 1))}>→</button></div>
    <div className="planning-calendar panel">{days.map((day) => { const key = localDate(day); const tasks = (events.data?.tasks ?? []).filter((task: any) => (task.start_at || task.deadline_at)?.slice(0, 10) === key); const blocks = (events.data?.time_blocks ?? []).filter((block: any) => block.starts_at.slice(0, 10) === key); return <section key={key} className={day.getMonth() === anchor.getMonth() ? '' : 'outside'}><header><strong>{day.getDate()}</strong><span>{day.toLocaleDateString('mn-MN', { weekday: 'short' })}</span></header>{tasks.map((task: any) => <article className="calendar-task" key={`task-${task.id}`}><strong>{task.title}</strong><small>{task.primary_owner_name || 'Хариуцагчгүй'} · {task.work_location || task.work_location_type || 'Байршилгүй'}</small><input aria-label="Эхлэх цаг" type="datetime-local" value={task.start_at?.slice(0,16) || ''} onChange={(event) => rescheduleTask(task, 'start_at', event.target.value)} /><input aria-label="Дуусах цаг" type="datetime-local" value={task.deadline_at?.slice(0,16) || ''} onChange={(event) => rescheduleTask(task, 'deadline_at', event.target.value)} /></article>)}{blocks.map((block: any) => <article className="calendar-block" key={`block-${block.id}`}><strong>{block.title}</strong><small>{new Date(block.starts_at).toLocaleTimeString('mn-MN', { hour: '2-digit', minute: '2-digit' })}–{new Date(block.ends_at).toLocaleTimeString('mn-MN', { hour: '2-digit', minute: '2-digit' })}</small><button aria-label="Устгах" onClick={() => deleteBlock.mutate(block.id)}><Trash2 size={12} /></button></article>)}</section> })}</div>
    {creating && <div className="sheet-backdrop" onMouseDown={() => setCreating(false)}><aside className="detail-sheet" onMouseDown={(event) => event.stopPropagation()}><div className="sheet-header"><div><span className="eyebrow">Private time block</span><h2>Хувийн цаг төлөвлөх</h2></div><CalendarDays /></div><form className="sheet-form" onSubmit={submit}><label>Гарчиг<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Эхлэх<input required type="datetime-local" value={form.starts_at} onChange={(event) => setForm({ ...form, starts_at: event.target.value })} /></label><label>Дуусах<input required type="datetime-local" value={form.ends_at} onChange={(event) => setForm({ ...form, ends_at: event.target.value })} /></label><button className="primary-action" disabled={createBlock.isPending}>Хадгалах</button></form></aside></div>}
  </div>
}
