import { useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { CalendarDays, Clock3, LayoutGrid, List, MapPin, Plus, Rows3, Save, UserRound, X } from 'lucide-react'
import { EnterpriseTask, useCreateEnterpriseTask, useEnterpriseTasks, useProjects, useUpdateEnterpriseTask, useWorkerDirectory, WorkflowStatus } from '../api/enterprise'
import { PeriodPreset, periodFromPreset, TimePeriodFilter } from '../components/TimePeriodFilter'

const COLUMNS: { key: WorkflowStatus; label: string }[] = [{ key: 'backlog', label: 'Backlog' }, { key: 'to_do', label: 'Хийх' }, { key: 'in_progress', label: 'Хийгдэж буй' }, { key: 'review', label: 'Хяналт' }, { key: 'done', label: 'Дууссан' }]
const EMPTY = { title: '', description: '', project_id: '', primary_owner_id: '', assignee_ids: [] as number[], workflow_status: 'to_do' as WorkflowStatus, priority: '2', start_at: '', deadline_at: '', estimate_minutes: '', work_location_type: '', work_location: '' }
function taskPlace(task: EnterpriseTask) { return task.work_location || (task.work_location_type === 'office' ? 'Оффис' : task.work_location_type === 'remote' ? 'Remote' : 'Байршилгүй') }

function TaskCard({ task, onOpen }: { task: EnterpriseTask; onOpen: () => void }) {
  return <button className="kanban-card task-card-clear" onClick={onOpen}><div className="task-priority" data-priority={task.priority} /><h3>{task.title}</h3><div className="task-facts"><span><UserRound size={13} />{task.primary_owner_name || 'Хариуцагчгүй'}</span><span><CalendarDays size={13} />{task.deadline_at ? new Date(task.deadline_at).toLocaleString('mn-MN') : 'Хугацаагүй'}</span><span><MapPin size={13} />{taskPlace(task)}</span><span>{task.project_name || 'Төсөлгүй'}</span></div></button>
}

export function EnterpriseTasksPage() {
  const params = new URLSearchParams(location.search)
  const projectId = params.get('project') ? Number(params.get('project')) : undefined
  const [periodPreset, setPeriodPreset] = useState<PeriodPreset | 'custom'>('month')
  const [period, setPeriod] = useState(() => periodFromPreset('month'))
  const [view, setView] = useState<'board' | 'list' | 'timeline' | 'calendar'>('board')
  const [selected, setSelected] = useState<EnterpriseTask | null>(null)
  const [creating, setCreating] = useState(false)
  const [form, setForm] = useState({ ...EMPTY, project_id: projectId ? String(projectId) : '' })
  const tasks = useEnterpriseTasks(projectId, period)
  const projects = useProjects()
  const workers = useWorkerDirectory()
  const createTask = useCreateEnterpriseTask()
  const updateTask = useUpdateEnterpriseTask()
  const grouped = useMemo(() => Object.fromEntries(COLUMNS.map((column) => [column.key, (tasks.data ?? []).filter((task) => task.workflow_status === column.key)])) as Record<WorkflowStatus, EnterpriseTask[]>, [tasks.data])
  const days = useMemo(() => { const result: Date[] = []; const cursor = new Date(`${period.date_from}T12:00:00`); const end = new Date(`${period.date_to}T12:00:00`); while (cursor <= end && result.length < 93) { result.push(new Date(cursor)); cursor.setDate(cursor.getDate() + 1) } return result }, [period])
  const payload = () => ({ title: form.title, description: form.description || null, project_id: form.project_id ? Number(form.project_id) : null, primary_owner_id: form.primary_owner_id ? Number(form.primary_owner_id) : null, assignee_ids: form.assignee_ids, workflow_status: form.workflow_status, priority: Number(form.priority), start_at: form.start_at ? new Date(form.start_at).toISOString() : null, deadline_at: form.deadline_at ? new Date(form.deadline_at).toISOString() : null, estimate_minutes: form.estimate_minutes ? Number(form.estimate_minutes) : null, work_location_type: (form.work_location_type || null) as EnterpriseTask['work_location_type'], work_location: form.work_location || null })
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await createTask.mutateAsync(payload()); setCreating(false); setForm({ ...EMPTY, project_id: projectId ? String(projectId) : '' }) } catch { /* mutation hook shows the server error */ } }
  const openTask = (task: EnterpriseTask) => { setSelected(task); setForm({ title: task.title, description: task.description || '', project_id: task.project_id ? String(task.project_id) : '', primary_owner_id: task.primary_owner_id ? String(task.primary_owner_id) : '', assignee_ids: task.assignee_ids || [], workflow_status: task.workflow_status, priority: String(task.priority), start_at: task.start_at?.slice(0,16) || '', deadline_at: task.deadline_at?.slice(0,16) || '', estimate_minutes: task.estimate_minutes ? String(task.estimate_minutes) : '', work_location_type: task.work_location_type || '', work_location: task.work_location || '' }) }
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; const data = payload(); try { await updateTask.mutateAsync({ id: selected.id, version: selected.version, ...data }); setSelected(null) } catch { /* mutation hook shows the server error */ } }
  const toggleAssignee = (id: number) => setForm({ ...form, assignee_ids: form.assignee_ids.includes(id) ? form.assignee_ids.filter((value) => value !== id) : [...form.assignee_ids, id] })
  const formFields = <><label>Юу хийх вэ?<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Тайлбар<textarea rows={4} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Хэн хариуцах вэ?<select value={form.primary_owner_id} onChange={(event) => setForm({ ...form, primary_owner_id: event.target.value })}><option value="">Хариуцагчгүй</option>{workers.data?.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><fieldset className="member-picker"><legend>Оролцогчид</legend>{workers.data?.map((worker) => <label key={worker.id}><input type="checkbox" checked={form.assignee_ids.includes(worker.id)} onChange={() => toggleAssignee(worker.id)} />{worker.name}</label>)}</fieldset><label>Төсөл<select value={form.project_id} onChange={(event) => setForm({ ...form, project_id: event.target.value })}><option value="">Төсөлгүй</option>{projects.data?.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="form-row"><label>Эхлэх<input type="datetime-local" value={form.start_at} onChange={(event) => setForm({ ...form, start_at: event.target.value })} /></label><label>Дуусах<input type="datetime-local" value={form.deadline_at} onChange={(event) => setForm({ ...form, deadline_at: event.target.value })} /></label></div><div className="form-row"><label>Ажлын газар<select value={form.work_location_type} onChange={(event) => setForm({ ...form, work_location_type: event.target.value })}><option value="">Байршилгүй</option><option value="office">Оффис</option><option value="remote">Remote</option><option value="custom">Бусад</option></select></label><label>Тодорхой байршил<input value={form.work_location} onChange={(event) => setForm({ ...form, work_location: event.target.value })} /></label></div><div className="form-row"><label>Төлөв<select value={form.workflow_status} onChange={(event) => setForm({ ...form, workflow_status: event.target.value as WorkflowStatus })}>{COLUMNS.map((column) => <option key={column.key} value={column.key}>{column.label}</option>)}</select></label><label>Тооцоолсон минут<input type="number" min="0" value={form.estimate_minutes} onChange={(event) => setForm({ ...form, estimate_minutes: event.target.value })} /></label></div></>
  return <div className="task-workspace"><div className="view-toolbar"><div><h2>Ажлын урсгал</h2><p>Хэн, хэзээ, хаана, юу хийх нь тодорхой харагдана.</p></div><div className="toolbar-cluster"><TimePeriodFilter preset={periodPreset} period={period} onChange={(next, value) => { setPeriodPreset(next); setPeriod(value) }} /><div className="segmented-control"><button className={view === 'board' ? 'active' : ''} onClick={() => setView('board')}><LayoutGrid size={15} />Самбар</button><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={15} />Жагсаалт</button><button className={view === 'timeline' ? 'active' : ''} onClick={() => setView('timeline')}><Rows3 size={15} />Timeline</button><button className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}><CalendarDays size={15} />Календарь</button></div><button className="primary-action compact" onClick={() => { setForm({ ...EMPTY, project_id: projectId ? String(projectId) : '' }); setCreating(true) }}><Plus size={16} />Даалгавар</button></div></div>
    {view === 'board' && <div className="kanban-board">{COLUMNS.map((column) => <section className="kanban-column" key={column.key}><header>{column.label}<b>{grouped[column.key].length}</b></header><div className="kanban-dropzone">{grouped[column.key].map((task) => <TaskCard key={task.id} task={task} onOpen={() => openTask(task)} />)}</div></section>)}</div>}
    {view === 'list' && <div className="task-list panel">{tasks.data?.map((task) => <TaskCard key={task.id} task={task} onOpen={() => openTask(task)} />)}</div>}
    {view === 'timeline' && <div className="task-timeline panel">{tasks.data?.map((task) => <button key={task.id} onClick={() => openTask(task)}><strong>{task.title}</strong><span>{task.start_at ? new Date(task.start_at).toLocaleDateString('mn-MN') : 'Эхлэх хугацаагүй'} → {task.deadline_at ? new Date(task.deadline_at).toLocaleDateString('mn-MN') : 'Дуусах хугацаагүй'}</span></button>)}</div>}
    {view === 'calendar' && <div className="task-calendar panel">{days.map((day) => { const key = day.toISOString().slice(0,10); const dayTasks = (tasks.data ?? []).filter((task) => (task.start_at || task.deadline_at)?.slice(0,10) === key); return <section key={key}><header><strong>{day.getDate()}</strong><span>{day.toLocaleDateString('mn-MN', { weekday: 'short' })}</span></header>{dayTasks.map((task) => <button key={task.id} onClick={() => openTask(task)}>{task.title}</button>)}</section> })}</div>}
    <AnimatePresence>{(selected || creating) && <motion.div className="sheet-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={() => { setSelected(null); setCreating(false) }}><motion.aside className="detail-sheet" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} onMouseDown={(event) => event.stopPropagation()}><div className="sheet-header"><div><span className="eyebrow">{selected ? `Task #${selected.id}` : 'Quick create'}</span><h2>{selected ? selected.title : 'Шинэ даалгавар'}</h2></div><button onClick={() => { setSelected(null); setCreating(false) }}><X /></button></div><form className="sheet-form" onSubmit={selected ? save : submit}>{formFields}<button className="primary-action" disabled={createTask.isPending || updateTask.isPending}>{selected ? <><Save size={16} />Хадгалах</> : 'Үүсгэх'}</button></form></motion.aside></motion.div>}</AnimatePresence>
  </div>
}
