import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { BarChart3, Boxes, BriefcaseBusiness, Calculator, CheckCircle2, ClipboardList, Factory, HeartPulse, Landmark, Plus, RotateCcw, ShieldCheck, ShoppingCart, Trash2, UsersRound, Wrench } from 'lucide-react'
import toast from 'react-hot-toast'
import { type ERPDocumentLineInput, type ERPDocumentView, type ERPFieldType, type ERPFormField, type ERPModule, useConvertERPDocument, useCreateERPDocument, useCreateERPMasterRequest, useERPDashboard, useERPDocumentAction, useERPDocuments, useERPForm, useERPMetadata, useSubmitERPDocument, useUpdateERPModules } from '../api/enterprise'

const MODULE_ICONS: Record<ERPModule, typeof Landmark> = { accounting: Calculator, selling: ShoppingCart, buying: BriefcaseBusiness, stock: Boxes, crm: UsersRound, support: HeartPulse, payroll: Landmark, manufacturing: Factory, assets_maintenance: Wrench }
const MODULE_DOCUMENTS: Record<ERPModule, Array<{ type: string; label: string }>> = {
  accounting: [{ type: 'journal_entry', label: 'Journal entries' }, { type: 'payment_entry', label: 'Payments' }, { type: 'budget', label: 'Budgets' }],
  selling: [{ type: 'quotation', label: 'Quotations' }, { type: 'sales_order', label: 'Sales orders' }, { type: 'sales_invoice', label: 'Sales invoices' }, { type: 'delivery', label: 'Delivery notes' }],
  buying: [{ type: 'supplier_quotation', label: 'RFQs' }, { type: 'purchase_order', label: 'Purchase orders' }, { type: 'purchase_invoice', label: 'Purchase invoices' }, { type: 'purchase_receipt', label: 'Goods receipt notes' }],
  stock: [{ type: 'stock_entry', label: 'Stock movements' }, { type: 'stock_reconciliation', label: 'Stock reconciliation' }],
  crm: [{ type: 'lead', label: 'Leads' }, { type: 'opportunity', label: 'Opportunities' }], support: [{ type: 'support_ticket', label: 'Customer tickets' }, { type: 'service_level_agreement', label: 'SLA policies' }],
  payroll: [], manufacturing: [{ type: 'bill_of_materials', label: 'Bills of materials' }, { type: 'work_order', label: 'Work orders' }, { type: 'job_card', label: 'Job cards' }], assets_maintenance: [{ type: 'asset', label: 'Assets' }, { type: 'maintenance_schedule', label: 'Maintenance schedules' }, { type: 'maintenance_visit', label: 'Maintenance visits' }],
}
const MASTER_OPERATIONS: Record<ERPModule, Array<{ operation: string; label: string; defaults: Record<string, unknown> }>> = {
  buying: [{ operation: 'supplier', label: 'Create supplier / vendor', defaults: { party_type: 'supplier', currency: 'MNT' } }, { operation: 'purchase_item', label: 'Create purchase item', defaults: { item_type: 'product', unit: 'Nos', valuation_method: 'moving_average', is_stock_item: true } }, { operation: 'supplier_price_list', label: 'Create supplier price list', defaults: { currency: 'MNT', minimum_quantity: 1, rate: 0 } }],
  selling: [{ operation: 'customer', label: 'Create customer', defaults: { party_type: 'customer', currency: 'MNT' } }, { operation: 'sales_catalog_item', label: 'Create sales catalog item', defaults: { item_type: 'product', unit: 'Nos', valuation_method: 'moving_average', is_stock_item: true } }, { operation: 'customer_discount_tier', label: 'Create customer discount tier', defaults: { minimum_spend: 0, discount_percent: 0 } }],
  stock: [{ operation: 'warehouse', label: 'Create warehouse', defaults: {} }, { operation: 'item_sku', label: 'Create item / SKU', defaults: { item_type: 'product', unit: 'Nos', valuation_method: 'moving_average', is_stock_item: true } }, { operation: 'uom', label: 'Create unit of measure', defaults: { decimal_places: 2 } }, { operation: 'reorder_rule', label: 'Create reorder rule', defaults: { reorder_level: 0, reorder_quantity: 0 } }],
  accounting: [{ operation: 'chart_account', label: 'Create chart of accounts entry', defaults: { account_type: 'expense', is_group: false } }, { operation: 'cost_center', label: 'Create cost center', defaults: {} }, { operation: 'tax_template', label: 'Create tax template', defaults: { direction: 'sales', rates: [] } }],
  crm: [], support: [], payroll: [], manufacturing: [], assets_maintenance: [],
}
const MONEY = (amount: string | number | undefined, currency = 'MNT') => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(amount || 0))

function CustomFieldInput({ field, value, onChange }: { field: ERPFormField; value: unknown; onChange: (value: unknown) => void }) {
  const type = field.field_type as ERPFieldType
  if (type === 'boolean') return <label className="erp-create-field checkbox"><input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} />{field.label}</label>
  if (type === 'select' || type === 'multi_select') return <label className="erp-create-field">{field.label}<select value={type === 'multi_select' ? '' : String(value ?? '')} multiple={type === 'multi_select'} onChange={(event) => onChange(type === 'multi_select' ? Array.from(event.currentTarget.selectedOptions).map((option) => option.value) : event.target.value)} required={field.required}><option value="">Select…</option>{(field.options.choices || []).map((choice: string) => <option key={choice}>{choice}</option>)}</select>{field.help_text && <small>{field.help_text}</small>}</label>
  if (type === 'long_text') return <label className="erp-create-field">{field.label}<textarea value={String(value ?? '')} onChange={(event) => onChange(event.target.value)} required={field.required} />{field.help_text && <small>{field.help_text}</small>}</label>
  return <label className="erp-create-field">{field.label}<input type={type === 'date' ? 'date' : type === 'datetime' ? 'datetime-local' : type === 'number' || type === 'money' ? 'number' : 'text'} value={String(value ?? '')} onChange={(event) => onChange(event.target.value)} required={field.required} />{field.help_text && <small>{field.help_text}</small>}</label>
}
export function lineTotal(line: ERPDocumentLineInput) { const gross = Number(line.quantity || 0) * Number(line.rate || 0); const discount = Number(line.discount_amount || 0) || gross * Number(line.discount_percent || 0) / 100; const net = Math.max(0, gross - discount); return net + net * Number(line.tax_rate || 0) / 100 }

export function ERPWorkspacePage() {
  const { t } = useTranslation(); const metadata = useERPMetadata(); const dashboard = useERPDashboard(Boolean(metadata.data && Object.values(metadata.data.modules).some(Boolean))); const updateModules = useUpdateERPModules()
  const enabledModules = useMemo(() => Object.entries(metadata.data?.modules ?? {}).filter(([, enabled]) => enabled).map(([module]) => module as ERPModule), [metadata.data]); const [module, setModule] = useState<ERPModule>('accounting'); const available = enabledModules.includes(module) ? module : enabledModules[0] || 'accounting'
  const [documentType, setDocumentType] = useState('journal_entry'); const [documentView, setDocumentView] = useState<ERPDocumentView>('all'); const [search, setSearch] = useState(''); const documents = useERPDocuments(documentType, Boolean(metadata.data?.modules[available]), documentView, search); const create = useCreateERPDocument(documentType); const submit = useSubmitERPDocument(documentType); const action = useERPDocumentAction(documentView === 'archived' ? 'restore' : 'archive', documentType); const convert = useConvertERPDocument(documentType); const form = useERPForm(documentType)
  const [creating, setCreating] = useState(false); const [custom, setCustom] = useState<Record<string, unknown>>({}); const [lineCustom, setLineCustom] = useState<Record<string, unknown>>({}); const [lines, setLines] = useState<ERPDocumentLineInput[]>([{ description: 'New line', quantity: 1, rate: 0, discount_percent: 0, discount_amount: 0, tax_rate: 0 }])
  const masterOptions = MASTER_OPERATIONS[available] || []; const [masterOperation, setMasterOperation] = useState(masterOptions[0]?.operation || 'item'); const selectedMaster = masterOptions.find((item) => item.operation === masterOperation) || masterOptions[0]; const masterForm = useERPForm(masterOperation); const createMasterRequest = useCreateERPMasterRequest(masterOperation); const [masterPayload, setMasterPayload] = useState<Record<string, unknown>>(selectedMaster?.defaults || { code: '', name: '' }); const [masterCustom, setMasterCustom] = useState<Record<string, unknown>>({})
  useEffect(() => { if (masterOptions.length && !masterOptions.some((item) => item.operation === masterOperation)) { setMasterOperation(masterOptions[0].operation); setMasterPayload({ ...masterOptions[0].defaults, code: '', name: '' }) } }, [available, masterOperation, masterOptions])
  const setMaster = (operation: string) => { const next = masterOptions.find((item) => item.operation === operation); setMasterOperation(operation); setMasterPayload({ ...(next?.defaults || {}), code: '', name: '' }); setMasterCustom({}) }
  const toggleModule = (target: ERPModule) => { if (!metadata.data) return; updateModules.mutate({ ...metadata.data.modules, [target]: !metadata.data.modules[target] }, { onSuccess: () => toast.success(t('erp.moduleUpdated', { defaultValue: 'ERP module visibility updated' })), onError: (error: any) => toast.error(error.response?.data?.detail || 'Module settings could not be updated') }) }
  const setDoc = (type: string) => { setDocumentType(type); setCreating(false); setDocumentView('all'); setSearch(''); setModule(Object.entries(MODULE_DOCUMENTS).find(([, entries]) => entries.some((item) => item.type === type))?.[0] as ERPModule || available) }
  const saveDraft = () => create.mutate({ custom, lines: lines.map((line) => ({ ...line, data: lineCustom })) }, { onSuccess: () => { toast.success(t('erp.draftCreated', { defaultValue: 'Draft created' })); setCreating(false); setCustom({}); setLineCustom({}); setLines([{ description: 'New line', quantity: 1, rate: 0, discount_percent: 0, discount_amount: 0, tax_rate: 0 }]) }, onError: (error: any) => toast.error(error.response?.data?.detail?.message || error.response?.data?.detail?.code || 'Draft could not be created') })
  const submitMaster = () => { if (!masterPayload.code && !masterPayload.item_id && !masterPayload.party_id) { toast.error(t('erp.requiredMaster', { defaultValue: 'Complete the required master-data fields' })); return } createMasterRequest.mutate({ payload: masterPayload, custom: masterCustom }, { onSuccess: () => { toast.success(t('erp.requestCreated', { defaultValue: 'Master-data request created' })); setMasterCustom({}) }, onError: (error: any) => toast.error(error.response?.data?.detail?.message || error.response?.data?.detail?.code || 'Request could not be created') }) }
  if (metadata.isLoading) return <div className="panel"><p>Loading ERP workspace…</p></div>; if (metadata.isError || !metadata.data) return <div className="panel"><h2>ERP is not available</h2><p>Your account does not yet have access to the ERP service.</p></div>
  return <div className="erp-workspace">
    <div className="view-toolbar"><div><span className="eyebrow">OYUNS ALL-IN-ONE · ERP</span><h2>{t('erp.title', { defaultValue: 'Business operations' })}</h2><p>{t('erp.subtitle', { defaultValue: 'Enable only the workflows your organization uses. Visibility does not replace permissions.' })}</p></div><BarChart3 /></div>
    <section className="erp-module-grid" aria-label={t('erp.modules', { defaultValue: 'ERP modules' })}>{(Object.keys(metadata.data.module_labels) as ERPModule[]).map((key) => { const Icon = MODULE_ICONS[key]; const enabled = metadata.data.modules[key]; return <article key={key} className={`panel erp-module-card ${enabled ? 'enabled' : ''}`}><Icon size={21} /><div><strong>{metadata.data.module_labels[key]}</strong><small>{enabled ? t('erp.visible', { defaultValue: 'Visible in workspace' }) : t('erp.hidden', { defaultValue: 'Hidden from workspace' })}</small></div><button className="erp-toggle" onClick={() => toggleModule(key)} disabled={updateModules.isPending} aria-label={`${metadata.data.module_labels[key]} ${enabled ? 'disable' : 'enable'}`}><span /></button></article> })}</section>
    <p className="erp-settings-notice"><ShieldCheck size={15} /> {t('erp.permissionNotice', { defaultValue: 'Module switches affect navigation and normal UI only. API, posting, audit, and integrations remain capability-controlled.' })} {metadata.data.modules.payroll && <Link to="/erp/payroll">Open dedicated Mongolia payroll</Link>}</p>
    {enabledModules.length === 0 ? <section className="panel erp-empty"><Boxes size={28} /><h3>{t('erp.noModules', { defaultValue: 'No ERP modules are visible' })}</h3><p>{t('erp.noModulesHelp', { defaultValue: 'An administrator can enable modules above to set up the business workspace.' })}</p></section> : <>
      <section className="erp-kpis">{[['Revenue', dashboard.data?.revenue], ['Expenses', dashboard.data?.expenses], ['Profit', dashboard.data?.profit], ['Inventory value', dashboard.data?.inventory_value], ['Open queries', String(dashboard.data?.open_queries ?? dashboard.data?.open_customer_queries ?? 0)], ['Payroll', dashboard.data?.payroll_total]].map(([label, value]) => <article className="panel" key={label}><small>{label}</small><strong>{label === 'Open queries' ? value : MONEY(value, metadata.data.currency)}</strong></article>)}</section>
      <section className="panel erp-master-request"><div className="view-toolbar"><div><span className="eyebrow">MASTER DATA REQUEST</span><h3>{t('erp.masterTitle', { defaultValue: 'Create contextual master data' })}</h3><p>{t('erp.masterSubtitle', { defaultValue: 'Approved requests are materialized into operational records with an audit trail.' })}</p></div><select aria-label="Master data operation" value={masterOperation} onChange={(event) => setMaster(event.target.value)}>{masterOptions.length ? masterOptions.map((item) => <option key={item.operation} value={item.operation}>{item.label}</option>) : <option value="item">Item</option>}</select></div>{masterOptions.length > 0 && <form className="erp-create-form" onSubmit={(event) => { event.preventDefault(); submitMaster() }}><div className="erp-create-fields">{['code', 'name'].map((key) => <label className="erp-create-field" key={key}>{key === 'code' ? 'Code' : 'Name'}<input value={String(masterPayload[key] || '')} onChange={(event) => setMasterPayload((current) => ({ ...current, [key]: event.target.value }))} required /></label>)}{masterOperation === 'supplier_price_list' && <><label className="erp-create-field">Supplier ID<input type="number" value={String(masterPayload.party_id || '')} onChange={(event) => setMasterPayload((current) => ({ ...current, party_id: Number(event.target.value) }))} required /></label><label className="erp-create-field">Item ID<input type="number" value={String(masterPayload.item_id || '')} onChange={(event) => setMasterPayload((current) => ({ ...current, item_id: Number(event.target.value) }))} required /></label><label className="erp-create-field">Rate<input type="number" min="0" value={String(masterPayload.rate || 0)} onChange={(event) => setMasterPayload((current) => ({ ...current, rate: event.target.value }))} /></label></>}{masterOperation === 'reorder_rule' && <><label className="erp-create-field">Item ID<input type="number" value={String(masterPayload.item_id || '')} onChange={(event) => setMasterPayload((current) => ({ ...current, item_id: Number(event.target.value) }))} required /></label><label className="erp-create-field">Warehouse ID<input type="number" value={String(masterPayload.warehouse_id || '')} onChange={(event) => setMasterPayload((current) => ({ ...current, warehouse_id: Number(event.target.value) }))} required /></label></>}{masterForm.data?.fields.filter((field) => field.section === 'master').map((field) => <CustomFieldInput key={field.key} field={field} value={masterCustom[field.key]} onChange={(value) => setMasterCustom((current) => ({ ...current, [field.key]: value }))} />)}</div><button className="primary-action compact" disabled={createMasterRequest.isPending}><Plus size={15} />{t('erp.submitRequest', { defaultValue: 'Submit request' })}</button></form>}</section>
      <section className="erp-document-panel panel"><div className="view-toolbar"><div><span className="eyebrow">DOCUMENT WORKBENCH</span><h3>{MODULE_DOCUMENTS[available].find((entry) => entry.type === documentType)?.label || 'Documents'}</h3></div><button className="primary-action compact" onClick={() => setCreating((value) => !value)} disabled={create.isPending}><Plus size={15} />{creating ? 'Close form' : 'New draft'}</button></div><div className="erp-document-tabs">{enabledModules.flatMap((enabledModule) => MODULE_DOCUMENTS[enabledModule]).map((entry) => <button key={entry.type} className={documentType === entry.type ? 'active' : ''} onClick={() => setDoc(entry.type)}>{entry.label}</button>)}</div><div className="erp-workbench-filters"><div className="erp-document-tabs" role="tablist">{(['all', 'drafts', 'pending_approval', 'approved', 'archived'] as ERPDocumentView[]).map((view) => <button key={view} className={documentView === view ? 'active' : ''} onClick={() => setDocumentView(view)}>{view === 'pending_approval' ? 'Pending approval' : view[0].toUpperCase() + view.slice(1)}</button>)}</div><input aria-label="Search documents" placeholder="Search documents…" value={search} onChange={(event) => setSearch(event.target.value)} /></div>
        {creating && <form className="erp-create-form" onSubmit={(event) => { event.preventDefault(); saveDraft() }}><div className="erp-create-fields">{form.data?.fields.filter((field) => field.section === 'header').map((field) => <CustomFieldInput key={field.key} field={field} value={custom[field.key]} onChange={(value) => setCustom((current) => ({ ...current, [field.key]: value }))} />)}</div><h4>Line items</h4>{lines.map((line, index) => <div className="erp-line-editor" key={index}><input aria-label={`Line ${index + 1} description`} value={line.description} onChange={(event) => setLines((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item))} /><input aria-label="Quantity" type="number" min="0" value={String(line.quantity ?? '')} onChange={(event) => setLines((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, quantity: event.target.value } : item))} /><input aria-label="Unit price" type="number" min="0" value={String(line.rate ?? '')} onChange={(event) => setLines((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, rate: event.target.value } : item))} /><input aria-label="Discount percent" type="number" min="0" max="100" value={String(line.discount_percent ?? 0)} onChange={(event) => setLines((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, discount_percent: event.target.value, discount_amount: 0 } : item))} /><input aria-label="VAT percent" type="number" min="0" max="100" value={String(line.tax_rate ?? 0)} onChange={(event) => setLines((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, tax_rate: event.target.value } : item))} /><strong>{MONEY(lineTotal(line), metadata.data.currency)}</strong><button type="button" className="icon-button" onClick={() => setLines((current) => current.length === 1 ? current : current.filter((_, itemIndex) => itemIndex !== index))} aria-label="Remove line"><Trash2 size={15} /></button></div>)}<button type="button" className="secondary-action compact" onClick={() => setLines((current) => [...current, { description: 'New line', quantity: 1, rate: 0, discount_percent: 0, discount_amount: 0, tax_rate: 0 }])}><Plus size={14} />Add line</button><div className="erp-form-total">Total <strong>{MONEY(lines.reduce((sum, line) => sum + lineTotal(line), 0), metadata.data.currency)}</strong></div><button className="primary-action compact" disabled={create.isPending}>Save draft</button></form>}
        {documents.isLoading ? <p>Loading documents…</p> : documents.isError ? <p>Document permission is required for this workspace.</p> : <div className="erp-document-list">{documents.data?.length ? documents.data.map((document) => <article key={document.id}><div><strong>{document.number}</strong><span>{document.workflow_state || document.status} · {document.posting_date}</span></div><div><strong>{MONEY(document.grand_total, document.currency)}</strong><div className="erp-row-actions">{documentView === 'archived' ? <button className="secondary-action compact" onClick={() => action.mutate(document.id)} disabled={action.isPending}><RotateCcw size={14} />Restore</button> : document.status === 'draft' && <button className="secondary-action compact" onClick={() => { if (window.confirm('Submit this document?')) submit.mutate(document.id) }} disabled={submit.isPending}><CheckCircle2 size={14} />Submit</button>}{documentView !== 'archived' && <button className="icon-button" onClick={() => { if (window.confirm('Archive this document?')) action.mutate(document.id) }} disabled={action.isPending} aria-label="Archive document"><RotateCcw size={14} /></button>}{(document.document_type === 'quotation' || document.document_type === 'sales_order' || document.document_type === 'supplier_quotation' || document.document_type === 'purchase_order') && <button className="secondary-action compact" onClick={() => convert.mutate({ id: document.id, targetType: document.document_type === 'quotation' ? 'sales_order' : document.document_type === 'sales_order' ? 'sales_invoice' : document.document_type === 'supplier_quotation' ? 'purchase_order' : 'purchase_invoice' })}>Convert</button>}</div></div></article>) : <div className="erp-empty"><ClipboardList size={24} /><p>{documentView === 'archived' ? 'No archived documents.' : 'No documents yet. Start with a draft.'}</p></div>}</div>}
      </section>
    </>}
  </div>
}
