import { useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { CalendarDays, Check, Copy, Download, Link2, Plus, Search, UserPlus, Users, X } from 'lucide-react'
import { downloadHRAttendanceCsv, useActor, usePayrollComponentMasters, useAddHRCompensation, useBulkUpdateHRAttendance, useCreateHREmployee, useDecideHRLeave, useGenerateHRPayroll, useHRCompensation, useHRDepartments, useHRAttendance, useHREmployees, useHRLeaveBalances, useHRLeaveRequests, useRegenerateHRInvite, useRevokeHRInvite, useSubmitHRLeave, useUpdateHRAttendance } from '../api/enterprise'
import type { HRAttendanceItem, HREmployee } from '../api/enterprise'
import { Badge, Btn, Card, Input, Modal, PageHeader, Select } from '../components/ui'

type Tab = 'directory' | 'leave' | 'attendance' | 'payroll'
const monthNow = () => new Date().toISOString().slice(0, 7)
const errorText = (error: any) => error?.response?.data?.detail?.message || error?.response?.data?.detail || 'Үйлдэл амжилтгүй боллоо'

export function HRWorkspacePage() {
  const actor = useActor()
  const isHR = Boolean(actor.data?.roles?.some((role) => role === 'admin' || role === 'hr'))
  const isManager = Boolean(actor.data?.roles?.some((role) => ['admin', 'hr', 'manager', 'team_lead'].includes(role)))
  const [tab, setTab] = useState<Tab>('directory')
  const [search, setSearch] = useState('')
  const [department, setDepartment] = useState('')
  const [selected, setSelected] = useState<HREmployee | null>(null)
  const [showAdd, setShowAdd] = useState(false)
  const [invite, setInvite] = useState<string | null>(null)
  const employees = useHREmployees({ search: search || undefined, department_id: department ? Number(department) : undefined })
  const departments = useHRDepartments()
  const leave = useHRLeaveRequests({ status: isManager ? undefined : undefined })
  const balances = useHRLeaveBalances({ employee_id: isHR ? undefined : actor.data?.employee_id || undefined })
  const attendance = useHRAttendance(monthNow())
  const visibleTabs = isHR ? (['directory', 'leave', 'attendance', 'payroll'] as Tab[]) : isManager ? (['directory', 'leave', 'attendance'] as Tab[]) : (['directory', 'leave', 'attendance'] as Tab[])
  const navLabels: Record<Tab, string> = { directory: 'Ажилтны лавлах', leave: 'Чөлөө', attendance: 'Ирц', payroll: 'Цалин' }
  return <div className="hr-workspace">
    <PageHeader title="Хүний нөөц" sub="Ажилтан, чөлөө, ирц ба цалингийн нэгдсэн орон зай">
      {isHR && <Btn variant="primary" onClick={() => setShowAdd(true)}><UserPlus size={15} />Ажилтан нэмэх</Btn>}
    </PageHeader>
    <nav className="hr-tabs" aria-label="HR sections">{visibleTabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{navLabels[item]}</button>)}</nav>
    {tab === 'directory' && <Directory employees={employees.data?.items || []} departments={departments.data || []} search={search} setSearch={setSearch} department={department} setDepartment={setDepartment} onSelect={setSelected} />}
    {tab === 'leave' && <LeavePanel isHR={isHR} isManager={isManager} balances={balances.data || []} requests={leave.data || []} employees={employees.data?.items || []} />}
    {tab === 'attendance' && <AttendancePanel items={attendance.data?.items || []} enabled={isManager} />}
    {tab === 'payroll' && isHR && <PayrollPanel />}
    {selected && <EmployeeDrawer employee={selected} isHR={isHR} onClose={() => setSelected(null)} onInvite={(url) => setInvite(url)} />}
    {showAdd && <AddWorkerModal departments={departments.data || []} onClose={() => setShowAdd(false)} onCreated={(url) => { setShowAdd(false); setInvite(url) }} />}
    {invite && <Modal title="Telegram урилга бэлэн" onClose={() => setInvite(null)}><div className="hr-invite-result"><p>Энэ холбоосыг ажилтанд илгээнэ үү. Нэг удаа ашиглагдана.</p><code>{invite}</code><div><Btn variant="primary" onClick={() => { void navigator.clipboard?.writeText(invite); toast.success('Хууллаа') }}><Copy size={14} />Хуулах</Btn><a className="secondary-action" href={invite} target="_blank" rel="noreferrer"><Link2 size={14} />Нээх</a></div></div></Modal>}
  </div>
}

function Directory({ employees, departments, search, setSearch, department, setDepartment, onSelect }: { employees: HREmployee[]; departments: { id: number; name: string }[]; search: string; setSearch: (value: string) => void; department: string; setDepartment: (value: string) => void; onSelect: (employee: HREmployee) => void }) {
  return <Card className="hr-directory-card"><div className="hr-toolbar"><label className="hr-search"><Search size={15} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Нэр, username, албан тушаалаар хайх…" /></label><Select value={department} onChange={setDepartment} options={[{ value: '', label: 'Бүх хэлтэс' }, ...departments.map((item) => ({ value: String(item.id), label: item.name }))]} /></div><div className="hr-directory-table"><table><thead><tr><th>Ажилтан</th><th>Албан тушаал</th><th>Хэлтэс</th><th>Telegram</th><th>Төлөв</th></tr></thead><tbody>{employees.map((employee) => <tr key={employee.id} onClick={() => onSelect(employee)}><td><div className="hr-person"><span>{(employee.first_name || employee.name || '?')[0]}</span><strong>{employee.name}</strong></div></td><td>{employee.job_title || employee.employment_role || '—'}</td><td>{employee.department_name || 'Тодорхойгүй'}</td><td>{employee.telegram_status === 'connected' ? <Badge color="green">Connected</Badge> : employee.telegram_status === 'pending_invite' ? <Badge color="yellow">Pending invite</Badge> : <Badge color="muted">Not invited</Badge>}</td><td><Badge color={employee.is_active ? 'green' : 'muted'}>{employee.is_active ? 'Идэвхтэй' : 'Идэвхгүй'}</Badge></td></tr>)}</tbody></table>{!employees.length && <div className="hr-empty">Ажилтан олдсонгүй</div>}</div></Card>
}

function AddWorkerModal({ departments, onClose, onCreated }: { departments: { id: number; name: string }[]; onClose: () => void; onCreated: (url: string) => void }) {
  const create = useCreateHREmployee(); const [form, setForm] = useState({ name: '', job_title: '', employment_role: '', department_id: '', start_date: '' })
  const submit = async () => { try { const result = await create.mutateAsync({ ...form, department_id: form.department_id ? Number(form.department_id) : null, start_date: form.start_date || null }); onCreated(result.invite.deep_link) } catch (error) { toast.error(errorText(error)) } }
  return <Modal title="Ажилтан нэмэх" onClose={onClose}><div className="hr-form-grid"><Input label="Нэр" value={form.name} onChange={(value) => setForm({ ...form, name: value })} fullWidth /><Input label="Албан тушаал" value={form.job_title} onChange={(value) => setForm({ ...form, job_title: value })} fullWidth /><Input label="Ажлын үүрэг / role" value={form.employment_role} onChange={(value) => setForm({ ...form, employment_role: value })} fullWidth /><Select label="Хэлтэс" value={form.department_id} onChange={(value) => setForm({ ...form, department_id: value })} options={[{ value: '', label: 'Сонгох' }, ...departments.map((item) => ({ value: String(item.id), label: item.name }))]} fullWidth /><Input label="Эхлэх огноо" type="date" value={form.start_date} onChange={(value) => setForm({ ...form, start_date: value })} fullWidth /></div><div className="hr-modal-actions"><Btn onClick={onClose}>Цуцлах</Btn><Btn variant="primary" onClick={submit} disabled={!form.name || create.isPending}><Plus size={14} />Урилгатай үүсгэх</Btn></div></Modal>
}

function EmployeeDrawer({ employee, isHR, onClose, onInvite }: { employee: HREmployee; isHR: boolean; onClose: () => void; onInvite: (url: string) => void }) {
  const regenerate = useRegenerateHRInvite(); const revoke = useRevokeHRInvite(); const compensation = useHRCompensation(employee.id); const masters = usePayrollComponentMasters(); const addCompensation = useAddHRCompensation();
  const [compForm, setCompForm] = useState({ component_master_id: '', amount: '', effective_from: monthNow() + '-01' });
  const inviteAgain = async () => { try { const result = await regenerate.mutateAsync(employee.id); onInvite(result.deep_link) } catch (error) { toast.error(errorText(error)) } }
  const add = async () => { if (!compForm.component_master_id || !compForm.amount || !compForm.effective_from) return; try { await addCompensation.mutateAsync({ employeeId: employee.id, component_master_id: Number(compForm.component_master_id), amount: compForm.amount, effective_from: compForm.effective_from }); toast.success('Бүрэлдэхүүн хадгалагдлаа'); setCompForm({ component_master_id: '', amount: '', effective_from: monthNow() + '-01' }) } catch (error) { toast.error(errorText(error)) } }
  return <div className="hr-drawer-backdrop" onClick={onClose}><aside className="hr-drawer" role="dialog" aria-label={`${employee.name} profile`} onClick={(event) => event.stopPropagation()}><header><div><span className="eyebrow">EMPLOYEE PROFILE</span><h2>{employee.name}</h2><p>{employee.telegram_username ? `@${employee.telegram_username.replace(/^@/, '')}` : 'Telegram холбогдоогүй'}</p></div><button onClick={onClose} aria-label="Хаах"><X size={18} /></button></header><section className="hr-drawer-section"><h3>Үндсэн мэдээлэл</h3><dl><dt>Хэлтэс</dt><dd>{employee.department_name || '—'}</dd><dt>Албан тушаал</dt><dd>{employee.job_title || '—'}</dd><dt>Эхлэх огноо</dt><dd>{employee.start_date || '—'}</dd><dt>Telegram</dt><dd>{employee.telegram_status}</dd></dl></section>{isHR && <><section className="hr-drawer-section"><h3>Урилга ба профайл</h3>{!employee.telegram_id && <><Btn variant="primary" onClick={inviteAgain} disabled={regenerate.isPending}><Link2 size={14} />Шинэ урилга үүсгэх</Btn>{employee.telegram_status === 'pending_invite' && <button className="secondary-action" onClick={() => revoke.mutate(employee.id)} disabled={revoke.isPending}>Урилгыг цуцлах</button>}</>}</section><section className="hr-drawer-section"><h3>Compensation</h3><div className="hr-component-list">{(compensation.data || []).map((item) => <div key={item.id}><strong>{item.component_name}</strong><span>{item.amount} MNT · {item.effective_from}</span></div>)}</div><div className="hr-form-grid"><Select label="Бүрэлдэхүүн" value={compForm.component_master_id} onChange={(value) => setCompForm({ ...compForm, component_master_id: value })} options={[{ value: '', label: 'Сонгох' }, ...(masters.data || []).map((item) => ({ value: String(item.id), label: item.name }))]} fullWidth /><Input label="Дүн (MNT)" type="number" value={compForm.amount} onChange={(value) => setCompForm({ ...compForm, amount: value })} fullWidth /><Input label="Хүчинтэй огноо" type="date" value={compForm.effective_from} onChange={(value) => setCompForm({ ...compForm, effective_from: value })} fullWidth /></div><Btn variant="primary" onClick={add} disabled={addCompensation.isPending || !compForm.component_master_id || !compForm.amount}><Plus size={14} />Хадгалах</Btn></section></>}</aside></div>
}

function LeavePanel({ isHR, isManager, balances, requests, employees }: { isHR: boolean; isManager: boolean; balances: any[]; requests: any[]; employees: HREmployee[] }) {
  const submit = useSubmitHRLeave(); const decide = useDecideHRLeave(); const [form, setForm] = useState({ employee_id: '', leave_type: 'annual', starts_on: '', ends_on: '', reason: '' })
  const ownBalances = balances.filter((item) => item.employee_id === balances[0]?.employee_id)
  const send = async () => { try { await submit.mutateAsync({ ...form, employee_id: form.employee_id ? Number(form.employee_id) : undefined }); toast.success('Чөлөөний хүсэлт илгээгдлээ'); setForm({ employee_id: '', leave_type: 'annual', starts_on: '', ends_on: '', reason: '' }) } catch (error) { toast.error(errorText(error)) } }
  return <div className="hr-panel-grid"><Card><div className="view-toolbar"><div><span className="eyebrow">TIME OFF</span><h2>Чөлөө хүсэх</h2></div><CalendarDays size={19} /></div><div className="hr-balance-grid">{ownBalances.map((item) => <div key={item.leave_type}><small>{item.leave_type}</small><strong>{item.available_days}</strong><span>боломжтой өдөр</span></div>)}</div><div className="hr-form-grid">{isHR && <Select label="Ажилтан" value={form.employee_id} onChange={(value) => setForm({ ...form, employee_id: value })} options={[{ value: '', label: 'Өөрийн нэр' }, ...employees.map((item) => ({ value: String(item.id), label: item.name }))]} fullWidth />}<Select label="Төрөл" value={form.leave_type} onChange={(value) => setForm({ ...form, leave_type: value })} options={[{ value: 'annual', label: 'Ээлжийн' }, { value: 'sick', label: 'Өвчтэй' }, { value: 'unpaid', label: 'Цалингүй' }]} fullWidth /><Input label="Эхлэх" type="date" value={form.starts_on} onChange={(value) => setForm({ ...form, starts_on: value })} fullWidth /><Input label="Дуусах" type="date" value={form.ends_on} onChange={(value) => setForm({ ...form, ends_on: value })} fullWidth /><Input label="Шалтгаан" value={form.reason} onChange={(value) => setForm({ ...form, reason: value })} fullWidth /></div><Btn variant="primary" onClick={send} disabled={!form.starts_on || !form.ends_on || !form.reason || submit.isPending}><Check size={14} />Илгээх</Btn></Card><Card><div className="view-toolbar"><div><span className="eyebrow">REQUESTS</span><h2>{isManager ? 'Хүсэлтийн дараалал' : 'Миний хүсэлтүүд'}</h2></div><Users size={19} /></div><div className="hr-request-list">{requests.map((item) => <article key={item.id}><div><strong>{item.employee_name}</strong><span>{item.leave_type} · {item.starts_on} – {item.ends_on} · {item.reason}</span></div><div className="hr-request-actions"><Badge color={item.status === 'approved' ? 'green' : item.status === 'rejected' ? 'red' : 'yellow'}>{item.status}</Badge>{isManager && item.status === 'pending' && <><button onClick={() => decide.mutate({ id: item.id, approve: true, version: item.version })} aria-label="Approve"><Check size={15} /></button><button onClick={() => { const feedback = window.prompt('Татгалзсан шалтгаан'); if (feedback) decide.mutate({ id: item.id, approve: false, feedback, version: item.version }) }} aria-label="Reject"><X size={15} /></button></>}</div></article>)}</div></Card></div>
}

function AttendancePanel({ items, enabled }: { items: HRAttendanceItem[]; enabled: boolean }) {
  const update = useUpdateHRAttendance(); const bulk = useBulkUpdateHRAttendance(); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState<string[]>([])
  const visible = useMemo(() => items.filter((item) => !filter || item.employee_name.toLowerCase().includes(filter.toLowerCase())), [items, filter])
  const setStatus = (item: HRAttendanceItem, status: string) => { if (!enabled || item.on_leave || !status) return; update.mutate({ employee_id: item.employee_id, attendance_date: item.attendance_date, status, version: item.version || undefined }) }
  const bulkStatus = (status: HRAttendanceItem['status']) => { if (!status || !selected.length) return; bulk.mutate(items.filter((item) => selected.includes(`${item.employee_id}-${item.attendance_date}`) && !item.on_leave).map((item) => ({ employee_id: item.employee_id, attendance_date: item.attendance_date, status, version: item.version || undefined })), { onSuccess: () => setSelected([]) }) }
  return <Card className="hr-attendance-card"><div className="view-toolbar"><div><span className="eyebrow">MONTHLY REGISTER</span><h2>Ирцийн баталгаажуулалт</h2><p>WorkTime-оос санал болгосон төлвийг шалгаж баталгаажуулна.</p></div><div className="hr-inline-actions"><button className="secondary-action" onClick={() => downloadHRAttendanceCsv(monthNow()).catch((error) => toast.error(errorText(error)))}><Download size={14} />CSV</button>{enabled && <><button className="secondary-action" disabled={!selected.length || bulk.isPending} onClick={() => bulkStatus('present')}>Сонгосныг ирсэн</button><button className="secondary-action" disabled={!selected.length || bulk.isPending} onClick={() => bulkStatus('remote')}>Remote</button></>}</div></div><label className="hr-search"><Search size={15} /><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Ажилтан хайх…" /></label><div className="hr-attendance-list">{visible.map((item) => { const key = `${item.employee_id}-${item.attendance_date}`; return <article key={key}><label className="hr-attendance-select"><input type="checkbox" checked={selected.includes(key)} disabled={!enabled || item.on_leave} onChange={() => setSelected((current) => current.includes(key) ? current.filter((value) => value !== key) : [...current, key])} /><span><strong>{item.employee_name}</strong><span>{item.attendance_date} · {item.worked_minutes} минут {item.on_leave ? '· Чөлөөтэй' : ''}</span></span></label><div className="hr-status-buttons">{(['present', 'remote', 'late', 'absent'] as const).map((status) => <button key={status} disabled={!enabled || item.on_leave || update.isPending} className={item.status === status ? 'active' : ''} onClick={() => setStatus(item, status)}>{status}</button>)}</div></article> })}</div></Card>
}

function PayrollPanel() {
  const components = usePayrollComponentMasters(); const generate = useGenerateHRPayroll(); const [form, setForm] = useState({ period_start: `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-01`, period_end: new Date().toISOString().slice(0, 10) })
  const run = async () => { try { const result = await generate.mutateAsync(form); toast.success(`Payroll Entry үүслээ: ${result.run_number}`) } catch (error) { toast.error(errorText(error)) } }
  return <div className="hr-panel-grid"><Card><div className="view-toolbar"><div><span className="eyebrow">MONTHLY PAYROLL</span><h2>Сарын цалин үүсгэх</h2><p>Батлагдсан цалингүй чөлөөг автоматаар суутгаж, existing Payroll Entry үүсгэнэ.</p></div></div><div className="hr-form-grid"><Input label="Эхлэх огноо" type="date" value={form.period_start} onChange={(value) => setForm({ ...form, period_start: value })} fullWidth /><Input label="Дуусах огноо" type="date" value={form.period_end} onChange={(value) => setForm({ ...form, period_end: value })} fullWidth /></div><Btn variant="primary" onClick={run} disabled={generate.isPending}><Plus size={14} />Payroll draft үүсгэх</Btn></Card><Card><div className="view-toolbar"><div><span className="eyebrow">COMPONENT MASTERS</span><h2>Давтамжит бүрэлдэхүүн</h2></div></div><div className="hr-component-list">{(components.data || []).map((item) => <div key={item.id}><strong>{item.name}</strong><span>{item.component_kind} · {item.code}</span></div>)}</div></Card></div>
}

export default HRWorkspacePage
