import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { Archive, BriefcaseBusiness, CalendarDays, Plus, Save, Users2, X } from 'lucide-react'
import { useArchiveProject, useCreateEnterpriseTask, useCreateProject, useEnterpriseTasks, useProject, useProjects, useUpdateProject, useWorkerDirectory } from '../api/enterprise'

const EMPTY = { code: '', name: '', description: '', status: 'active', manager_id: '', member_ids: [] as number[], starts_on: '', ends_on: '', budget_minutes: '', budget_amount: '', currency: 'MNT' }

export function ProjectsWorkspacePage() {
  const projects = useProjects(); const workers = useWorkerDirectory(); const createProject = useCreateProject()
  const [creating, setCreating] = useState(false); const [selectedId, setSelectedId] = useState<number>(); const [form, setForm] = useState(EMPTY)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await createProject.mutateAsync({ ...form, manager_id: form.manager_id ? Number(form.manager_id) : null, member_ids: form.member_ids, starts_on: form.starts_on || null, ends_on: form.ends_on || null, budget_minutes: form.budget_minutes ? Number(form.budget_minutes) : null, budget_amount: form.budget_amount ? Number(form.budget_amount) : null }); setForm(EMPTY); setCreating(false) } catch { /* hook reports */ } }
  const toggleMember = (id: number) => setForm({ ...form, member_ids: form.member_ids.includes(id) ? form.member_ids.filter((value) => value !== id) : [...form.member_ids, id] })
  return <div className="projects-workspace"><div className="view-toolbar"><div><h2>Төслийн портфолио</h2><p>Төсөл, баг, хугацаа, даалгавар болон дэд даалгаврыг нэг дор удирдана.</p></div><button className="primary-action" onClick={() => { setForm(EMPTY); setCreating(true) }}><Plus size={17} />Шинэ төсөл</button></div>
    <div className="project-grid">{projects.data?.map((project) => <button className="project-card panel project-card-button" key={project.id} onClick={() => setSelectedId(project.id)}><div className="project-card-top"><div className="project-icon"><BriefcaseBusiness /></div><span className={`status-pill ${project.status}`}>{project.status}</span></div><span className="eyebrow">{project.code}</span><h3>{project.name}</h3><p>{project.description || 'Тайлбаргүй'}</p><div className="project-stats"><div className="project-stat"><CalendarDays size={16} /><span>Хугацаа</span><strong>{project.ends_on || 'Тодорхойгүй'}</strong></div><div className="project-stat"><Users2 size={16} /><span>Хариуцагч</span><strong>{project.manager_name || 'Томилоогүй'}</strong></div></div><footer><span>{project.member_ids?.length || 0} гишүүн</span><strong>Нээх</strong></footer></button>)}</div>
    <AnimatePresence>{creating && <Sheet onClose={() => setCreating(false)} title="Шинэ төсөл" eyebrow="New project"><form className="sheet-form" onSubmit={submit}><ProjectFields form={form} setForm={setForm} workers={workers.data || []} toggleMember={toggleMember} /><button className="primary-action" disabled={createProject.isPending}>Төсөл үүсгэх</button></form></Sheet>}</AnimatePresence>
    <AnimatePresence>{selectedId && <ProjectDrawer id={selectedId} onClose={() => setSelectedId(undefined)} />}</AnimatePresence>
  </div>
}

function ProjectDrawer({ id, onClose }: { id: number; onClose: () => void }) {
  const project = useProject(id); const tasks = useEnterpriseTasks(id, undefined, { scope: 'project' }); const workers = useWorkerDirectory(); const update = useUpdateProject(); const archive = useArchiveProject(); const createTask = useCreateEnterpriseTask()
  const [tab, setTab] = useState<'overview' | 'tasks' | 'settings'>('overview'); const [form, setForm] = useState(EMPTY); const [taskTitle, setTaskTitle] = useState(''); const [parentId, setParentId] = useState<number>()
  useEffect(() => { if (project.data) setForm({ code: project.data.code, name: project.data.name, description: project.data.description || '', status: project.data.status, manager_id: project.data.manager_id ? String(project.data.manager_id) : '', member_ids: project.data.member_ids || [], starts_on: project.data.starts_on || '', ends_on: project.data.ends_on || '', budget_minutes: project.data.budget_minutes ? String(project.data.budget_minutes) : '', budget_amount: project.data.budget_amount ? String(project.data.budget_amount) : '', currency: project.data.currency }) }, [project.data])
  const toggleMember = (employeeId: number) => setForm({ ...form, member_ids: form.member_ids.includes(employeeId) ? form.member_ids.filter((value) => value !== employeeId) : [...form.member_ids, employeeId] })
  const save = async (event: React.FormEvent) => { event.preventDefault(); await update.mutateAsync({ id, ...form, manager_id: form.manager_id ? Number(form.manager_id) : null, starts_on: form.starts_on || null, ends_on: form.ends_on || null, budget_minutes: form.budget_minutes ? Number(form.budget_minutes) : null, budget_amount: form.budget_amount ? Number(form.budget_amount) : null }) }
  const addTask = async (event: React.FormEvent) => { event.preventDefault(); await createTask.mutateAsync({ title: taskTitle, project_id: id, parent_task_id: parentId || null, workflow_status: 'to_do' }); setTaskTitle(''); setParentId(undefined) }
  return <Sheet onClose={onClose} title={project.data?.name || 'Төсөл'} eyebrow={project.data?.code || 'Project'}><div className="project-drawer-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Тойм</button><button className={tab === 'tasks' ? 'active' : ''} onClick={() => setTab('tasks')}>Даалгавар</button>{project.data?.can_archive && <button className={tab === 'settings' ? 'active' : ''} onClick={() => setTab('settings')}>Тохиргоо</button>}</div>
    {tab === 'overview' && project.data && <div className="project-overview"><p>{project.data.description || 'Тайлбар оруулаагүй байна.'}</p><div><span>Төлөв<strong>{project.data.status}</strong></span><span>Дуусах<strong>{project.data.ends_on || 'Хугацаагүй'}</strong></span><span>Гишүүд<strong>{project.data.member_ids.length}</strong></span><span>Даалгавар<strong>{tasks.data?.length || 0}</strong></span></div></div>}
    {tab === 'tasks' && <div className="project-task-panel"><form onSubmit={addTask}><input required value={taskTitle} onChange={(event) => setTaskTitle(event.target.value)} placeholder={parentId ? 'Шинэ дэд даалгавар' : 'Шинэ төслийн даалгавар'} /><button className="primary-action compact"><Plus size={15} />{parentId ? 'Дэд даалгавар' : 'Даалгавар'}</button>{parentId && <button type="button" className="secondary-action compact" onClick={() => setParentId(undefined)}>Цуцлах</button>}</form>{tasks.data?.map((task) => <article key={task.id} className={task.parent_task_id ? 'project-subtask' : ''}><div><strong>{task.title}</strong><small>{task.parent_task_id ? 'Дэд даалгавар' : task.workflow_status}</small></div>{!task.parent_task_id && <button onClick={() => setParentId(task.id)}><Plus size={14} />Дэд даалгавар</button>}</article>)}</div>}
    {tab === 'settings' && project.data?.can_archive && <form className="sheet-form" onSubmit={save}><ProjectFields form={form} setForm={setForm} workers={workers.data || []} toggleMember={toggleMember} /><button className="primary-action" disabled={update.isPending}><Save size={16} />Хадгалах</button><button type="button" className="danger-action" onClick={async () => { if (!window.confirm('Төслийг архивлах уу? Даалгаврууд хадгалагдана.')) return; await archive.mutateAsync(id); onClose() }}><Archive size={16} />Төсөл устгах</button></form>}
  </Sheet>
}

function ProjectFields({ form, setForm, workers, toggleMember }: { form: typeof EMPTY; setForm: (value: typeof EMPTY) => void; workers: { id: number; name: string }[]; toggleMember: (id: number) => void }) {
  return <><div className="form-row"><label>Код<input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} required /></label><label>Төлөв<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="draft">Draft</option><option value="planned">Planned</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label></div><label>Нэр<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Тайлбар<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} rows={3} /></label><label>Хариуцагч<select value={form.manager_id} onChange={(event) => setForm({ ...form, manager_id: event.target.value })}><option value="">Томилоогүй</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><fieldset className="member-picker"><legend>Төслийн гишүүд</legend>{workers.map((worker) => <label key={worker.id}><input type="checkbox" checked={form.member_ids.includes(worker.id)} onChange={() => toggleMember(worker.id)} />{worker.name}</label>)}</fieldset><div className="form-row"><label>Эхлэх огноо<input type="date" value={form.starts_on} onChange={(event) => setForm({ ...form, starts_on: event.target.value })} /></label><label>Дуусах огноо<input type="date" value={form.ends_on} onChange={(event) => setForm({ ...form, ends_on: event.target.value })} /></label></div><div className="form-row"><label>Цагийн төсөв<input type="number" min="0" value={form.budget_minutes} onChange={(event) => setForm({ ...form, budget_minutes: event.target.value })} /></label><label>Мөнгөн төсөв<input type="number" min="0" value={form.budget_amount} onChange={(event) => setForm({ ...form, budget_amount: event.target.value })} /></label></div></>
}

function Sheet({ onClose, title, eyebrow, children }: { onClose: () => void; title: string; eyebrow: string; children: React.ReactNode }) { return <motion.div className="sheet-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.aside className="detail-sheet" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', bounce: 0, duration: .4 }} onMouseDown={(event) => event.stopPropagation()}><div className="sheet-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button onClick={onClose}><X /></button></div>{children}</motion.aside></motion.div> }
