import { useTranslation } from 'react-i18next'
import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { AnimatePresence, motion } from 'motion/react'
import { Archive, BriefcaseBusiness, CalendarDays, Check, Plus, Save, Search, Users2, X } from 'lucide-react'
import { EnterpriseTask, WorkflowStatus, useArchiveProject, useCreateEnterpriseTask, useCreateProject, useEnterpriseTasks, useProject, useProjects, useUpdateProject, useWorkerDirectory } from '../api/enterprise'
import { QueryRegion, Skeleton, toQueryRegionState } from '../components/Loading'
import { UserTagPicker } from '../components/UserTagPicker'
import { CreateButton } from '../components/CreateButton'

const EMPTY = { code: '', name: '', description: '', status: 'active', manager_id: '', member_ids: [] as number[], starts_on: '', ends_on: '', budget_minutes: '', budget_amount: '', currency: 'MNT' }

export function ProjectsWorkspacePage() {
  const { t } = useTranslation()
  const projects = useProjects(); const workers = useWorkerDirectory(); const createProject = useCreateProject()
  const [creating, setCreating] = useState(false); const [selectedId, setSelectedId] = useState<number>(); const [form, setForm] = useState(EMPTY); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('all')
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await createProject.mutateAsync({ ...form, manager_id: form.manager_id ? Number(form.manager_id) : null, member_ids: form.member_ids, starts_on: form.starts_on || null, ends_on: form.ends_on || null, budget_minutes: form.budget_minutes ? Number(form.budget_minutes) : null, budget_amount: form.budget_amount ? Number(form.budget_amount) : null }); setForm(EMPTY); setCreating(false) } catch { /* hook reports */ } }
  const toggleMember = (id: number) => setForm({ ...form, member_ids: form.member_ids.includes(id) ? form.member_ids.filter((value) => value !== id) : [...form.member_ids, id] })
  const visibleProjects = projects.data?.filter((project) => { const query = search.trim().toLowerCase(); const matchesSearch = !query || `${project.code} ${project.name} ${project.description || ''}`.toLowerCase().includes(query); const matchesStatus = statusFilter === 'all' || project.status === statusFilter; return matchesSearch && matchesStatus }) ?? []; const ongoing = visibleProjects.filter((project) => project.status !== 'completed'); const completed = visibleProjects.filter((project) => project.status === 'completed')
  const cards = (items: typeof ongoing) => <div className="project-grid">{items.map((project) => <button className="project-card panel project-card-button" key={project.id} onClick={() => setSelectedId(project.id)}><div className="project-card-top"><div className="project-icon"><BriefcaseBusiness /></div><span className={`status-pill ${project.status}`}>{project.status}</span></div><span className="eyebrow">{project.code}</span><h3>{project.name}</h3><p>{project.description || t('projects.noDescription')}</p><div className="project-stats"><div className="project-stat"><CalendarDays size={16} /><span>{t('projects.period')}</span><strong>{project.ends_on || t('projects.unknown')}</strong></div><div className="project-stat"><Users2 size={16} /><span>{t('projects.owner')}</span><strong>{project.manager_name || t('projects.unassigned')}</strong></div></div><footer><span>{t('projects.memberCount', { n: project.member_ids?.length || 0 })}</span><strong>{t('projects.open')}</strong></footer></button>)}</div>
  return <div className="projects-workspace"><div className="workspace-toolbar projects-toolbar"><div className="toolbar-start project-tools"><label className="toolbar-search"><Search size={15} /><span className="sr-only">{t('projects.search')}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('projects.search')} /></label><select aria-label={t('projects.filterStatus')} value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">{t('projects.allStatuses')}</option><option value="active">{t('projects.status.active')}</option><option value="planned">{t('projects.status.planned')}</option><option value="on_hold">{t('projects.status.paused')}</option><option value="completed">{t('projects.status.completed')}</option></select></div><CreateButton label={t('projects.new')} onClick={() => { setForm(EMPTY); setCreating(true) }} /></div>
    <QueryRegion state={toQueryRegionState(projects)} empty={Boolean(projects.data && projects.data.length === 0)} emptyFallback={<p className="query-region-state">{t('projects.empty')}</p>} skeleton={<div className="project-grid"><Skeleton variant="card" count={6} /></div>}>
      {cards(ongoing)}
      {completed.length > 0 && <section className="completed-projects"><header><h3>{t('projects.completedList')}</h3><span>{completed.length}</span></header>{cards(completed)}</section>}
    </QueryRegion>
    <AnimatePresence>{creating && <Sheet onClose={() => setCreating(false)} title={t('projects.new')} eyebrow="New project"><form className="sheet-form" onSubmit={submit}><ProjectFields form={form} setForm={setForm} workers={workers.data || []} toggleMember={toggleMember} /><button className="primary-action" disabled={createProject.isPending}>{t('projects.create')}</button></form></Sheet>}</AnimatePresence>
    <AnimatePresence>{selectedId && <ProjectDrawer id={selectedId} onClose={() => setSelectedId(undefined)} />}</AnimatePresence>
  </div>
}

function ProjectDrawer({ id, onClose }: { id: number; onClose: () => void }) {
  const { t } = useTranslation()
  const project = useProject(id); const tasks = useEnterpriseTasks(id, undefined, { scope: 'project' }); const workers = useWorkerDirectory(); const update = useUpdateProject(); const archive = useArchiveProject(); const createTask = useCreateEnterpriseTask()
  const [tab, setTab] = useState<'overview' | 'tasks' | 'settings'>('tasks'); const [creatingTask, setCreatingTask] = useState(false); const [form, setForm] = useState(EMPTY); const [taskForm, setTaskForm] = useState({ title: '', description: '', primary_owner_id: '', assignee_ids: [] as number[], workflow_status: 'to_do' as WorkflowStatus, priority: '2', start_at: '', deadline_at: '', estimate_minutes: '', work_location_type: '', work_location: '' })
  useEffect(() => { if (project.data) setForm({ code: project.data.code, name: project.data.name, description: project.data.description || '', status: project.data.status, manager_id: project.data.manager_id ? String(project.data.manager_id) : '', member_ids: project.data.member_ids || [], starts_on: project.data.starts_on || '', ends_on: project.data.ends_on || '', budget_minutes: project.data.budget_minutes ? String(project.data.budget_minutes) : '', budget_amount: project.data.budget_amount ? String(project.data.budget_amount) : '', currency: project.data.currency }) }, [project.data])
  const toggleMember = (employeeId: number) => setForm({ ...form, member_ids: form.member_ids.includes(employeeId) ? form.member_ids.filter((value) => value !== employeeId) : [...form.member_ids, employeeId] })
  const save = async (event: React.FormEvent) => { event.preventDefault(); await update.mutateAsync({ id, ...form, manager_id: form.manager_id ? Number(form.manager_id) : null, starts_on: form.starts_on || null, ends_on: form.ends_on || null, budget_minutes: form.budget_minutes ? Number(form.budget_minutes) : null, budget_amount: form.budget_amount ? Number(form.budget_amount) : null }) }
  const addTask = async (event: React.FormEvent) => { event.preventDefault(); try { await createTask.mutateAsync({ ...taskForm, project_id: id, primary_owner_id: taskForm.primary_owner_id ? Number(taskForm.primary_owner_id) : null, priority: Number(taskForm.priority), start_at: taskForm.start_at ? new Date(taskForm.start_at).toISOString() : null, deadline_at: taskForm.deadline_at ? new Date(taskForm.deadline_at).toISOString() : null, estimate_minutes: taskForm.estimate_minutes ? Number(taskForm.estimate_minutes) : null, work_location_type: (taskForm.work_location_type || null) as EnterpriseTask['work_location_type'], work_location: taskForm.work_location || null }); setTaskForm({ title: '', description: '', primary_owner_id: '', assignee_ids: [], workflow_status: 'to_do', priority: '2', start_at: '', deadline_at: '', estimate_minutes: '', work_location_type: '', work_location: '' }); setCreatingTask(false); setTab('tasks') } catch { /* hook reports */ } }
  const complete = async () => { await update.mutateAsync({ id, status: 'completed' }); onClose() }
  return <Sheet onClose={onClose} title={project.data?.name || t('projects.project')} eyebrow={project.data?.code || 'Project'} actions={!creatingTask && <button type="button" className="primary-action project-task-create" onClick={() => setCreatingTask(true)}><Plus size={16} />{t('projects.createTask')}</button>}><div className="project-drawer-tabs"><button type="button" className={tab === 'overview' ? 'active' : ''} onClick={() => { setCreatingTask(false); setTab('overview') }}>{t('projects.tab.overview')}</button><button type="button" className={tab === 'tasks' ? 'active' : ''} onClick={() => { setCreatingTask(false); setTab('tasks') }}>{t('projects.tab.tasks')}</button><button type="button" className={tab === 'settings' ? 'active' : ''} onClick={() => { setCreatingTask(false); setTab('settings') }}>{t('projects.tab.settings')}</button></div>
    {creatingTask ? <section className="project-task-create-form"><div className="section-heading"><div><span className="eyebrow">{t('projects.newTaskEyebrow')}</span><h3>{t('projects.newTask')}</h3></div><button className="text-action" type="button" onClick={() => setCreatingTask(false)}>{t('projects.cancel')}</button></div><form className="sheet-form" onSubmit={addTask}><ProjectTaskFields form={taskForm} setForm={setTaskForm} workers={workers.data || []} /><button className="primary-action" disabled={createTask.isPending}><Plus size={15} />{t('projects.createTask')}</button></form></section> : <>
      {tab === 'overview' && project.data && <div className="project-overview"><p>{project.data.description || t('projects.noDescriptionYet')}</p><div><span>{t('projects.statusLabel')}<strong>{project.data.status}</strong></span><span>{t('projects.due')}<strong>{project.data.ends_on || t('projects.noDeadline')}</strong></span><span>{t('projects.members')}<strong>{project.data.member_ids.length}</strong></span><span>{t('projects.tab.tasks')}<strong>{tasks.data?.length || 0}</strong></span></div>{project.data.can_archive && project.data.status !== 'completed' && <button className="primary-action" onClick={complete} disabled={update.isPending}><Check size={16} />{t('projects.complete')}</button>}</div>}
      {tab === 'tasks' && <div className="project-task-panel">{tasks.data?.filter((task) => !task.parent_task_id).map((task) => <article key={task.id}><div><strong>{task.title}</strong><small>{task.workflow_status}</small></div></article>)}{tasks.data?.length === 0 && <p className="project-task-empty">{t('projects.noTasks')}</p>}</div>}
      {tab === 'settings' && (project.data?.can_archive ? <form className="sheet-form" onSubmit={save}><ProjectFields form={form} setForm={setForm} workers={workers.data || []} toggleMember={toggleMember} /><button className="primary-action" disabled={update.isPending}><Save size={16} />{t('projects.save')}</button><button type="button" className="danger-action" onClick={async () => { if (!window.confirm(t('projects.archiveConfirm'))) return; await archive.mutateAsync(id); onClose() }}><Archive size={16} />{t('projects.delete')}</button></form> : <p className="project-settings-notice">{t('projects.settingsOwnerOnly')}</p>)}
    </>}
  </Sheet>
}

function ProjectFields({ form, setForm, workers }: { form: typeof EMPTY; setForm: (value: typeof EMPTY) => void; workers: { id: number; name: string }[]; toggleMember?: (id: number) => void }) {
  const { t } = useTranslation()
  return <><div className="form-row"><label>{t('projects.code')}<input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} required /></label><label>{t('projects.statusLabel')}<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="draft">{t('projects.status.draft')}</option><option value="planned">{t('projects.status.plannedOne')}</option><option value="active">{t('projects.status.activeOne')}</option><option value="on_hold">{t('projects.status.onHold')}</option><option value="completed">{t('projects.status.completedOne')}</option><option value="cancelled">{t('projects.status.cancelled')}</option></select></label></div><label>{t('projects.name')}<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>{t('projects.description')}<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} rows={3} /></label><label>{t('projects.owner')}<select value={form.manager_id} onChange={(event) => setForm({ ...form, manager_id: event.target.value })}><option value="">{t('projects.unassigned')}</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><UserTagPicker label={t('projects.membersLabel')} value={form.member_ids} users={workers} onChange={(member_ids) => setForm({ ...form, member_ids })} /><div className="form-row"><label>{t('projects.startDate')}<input type="date" value={form.starts_on} onChange={(event) => setForm({ ...form, starts_on: event.target.value })} /></label><label>{t('projects.endDate')}<input type="date" value={form.ends_on} onChange={(event) => setForm({ ...form, ends_on: event.target.value })} /></label></div><div className="form-row"><label>{t('projects.hoursBudget')}<input type="number" min="0" value={form.budget_minutes} onChange={(event) => setForm({ ...form, budget_minutes: event.target.value })} /></label><label>{t('projects.moneyBudget')}<input type="number" min="0" value={form.budget_amount} onChange={(event) => setForm({ ...form, budget_amount: event.target.value })} /></label></div></>
}

function ProjectTaskFields({ form, setForm, workers }: { form: { title: string; description: string; primary_owner_id: string; assignee_ids: number[]; workflow_status: WorkflowStatus; priority: string; start_at: string; deadline_at: string; estimate_minutes: string; work_location_type: string; work_location: string }; setForm: React.Dispatch<React.SetStateAction<typeof form>>; workers: { id: number; name: string }[] }) {
  const { t } = useTranslation()
  const toggle = (id: number) => setForm((value) => ({ ...value, assignee_ids: value.assignee_ids.includes(id) ? value.assignee_ids.filter((item) => item !== id) : [...value.assignee_ids, id] }))
  const allAssigned = workers.length > 0 && form.assignee_ids.length === workers.length
  return <><label>{t('projects.task.what')}<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>{t('projects.description')}<textarea rows={4} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>{t('projects.task.who')}<select value={form.primary_owner_id} onChange={(event) => setForm({ ...form, primary_owner_id: event.target.value })}><option value="">{t('projects.task.noOwner')}</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><fieldset className="member-picker"><legend>{t('projects.task.participants')}</legend><label><input type="checkbox" checked={allAssigned} onChange={(event) => setForm({ ...form, assignee_ids: event.target.checked ? workers.map((worker) => worker.id) : [] })} />{t('projects.task.everyone')}</label>{workers.map((worker) => <label key={worker.id}><input type="checkbox" checked={form.assignee_ids.includes(worker.id)} onChange={() => toggle(worker.id)} />{worker.name}</label>)}</fieldset><div className="form-row"><label>{t('projects.task.start')}<input type="datetime-local" value={form.start_at} onChange={(event) => setForm({ ...form, start_at: event.target.value })} /></label><label>{t('projects.due')}<input type="datetime-local" value={form.deadline_at} onChange={(event) => setForm({ ...form, deadline_at: event.target.value })} /></label></div><div className="form-row"><label>{t('projects.task.where')}<select value={form.work_location_type} onChange={(event) => setForm({ ...form, work_location_type: event.target.value })}><option value="">{t('projects.task.noLocation')}</option><option value="office">{t('projects.task.office')}</option><option value="remote">{t('projects.task.remote')}</option><option value="custom">{t('projects.task.specific')}</option></select></label><label>{t('projects.task.locationDetails')}<input value={form.work_location} onChange={(event) => setForm({ ...form, work_location: event.target.value })} disabled={form.work_location_type !== 'custom'} /></label></div><div className="form-row"><label>{t('projects.statusLabel')}<select value={form.workflow_status} onChange={(event) => setForm({ ...form, workflow_status: event.target.value as WorkflowStatus })}><option value="backlog">{t('projects.task.backlog')}</option><option value="to_do">{t('projects.task.todo')}</option><option value="in_progress">{t('projects.task.inProgress')}</option><option value="review">{t('projects.task.review')}</option><option value="done">{t('projects.task.done')}</option></select></label><label>{t('projects.task.estimate')}<input type="number" min="0" value={form.estimate_minutes} onChange={(event) => setForm({ ...form, estimate_minutes: event.target.value })} /></label></div></>
}

function Sheet({ onClose, title, eyebrow, children, actions }: { onClose: () => void; title: string; eyebrow: string; children: React.ReactNode; actions?: React.ReactNode }) { const { t } = useTranslation(); return createPortal(<motion.div className="sheet-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.aside className="detail-sheet" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', bounce: 0, duration: .4 }} onMouseDown={(event) => event.stopPropagation()}><div className="sheet-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><div className="sheet-header-actions">{actions}<button type="button" aria-label={t('projects.close')} onClick={onClose}><X /></button></div></div>{children}</motion.aside></motion.div>, document.body) }
