import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { downloadPayrollReport, downloadPayrollSalaryRegister, usePayrollBankRemittance, usePayrollCapabilities, usePayrollPeriodGLTotals, usePayrollPeriods, usePayrollReport, usePayrollRunPayslips, usePayrollRuns, usePayrollSalaryRegister } from '../../api/enterprise'
import { formatPayrollMoney, PayrollShell, payrollDocumentStatusLabel } from '../../pages/PayrollWorkspacePage'

export function PayrollDocumentsPage({ kind }: { kind: 'slips' | 'reports' }) {
  const [params, setParams] = useSearchParams()
  const runs = usePayrollRuns()
  const periods = usePayrollPeriods()
  const permissions = usePayrollCapabilities()
  const flags = permissions.data?.capabilities || {}
  const runId = Number(params.get('run') || runs.data?.[0]?.id || 0) || undefined
  const view = params.get('view') || 'statutory'
  const periodId = Number(params.get('period') || runs.data?.find((row) => row.id === runId)?.payroll_period_id || periods.data?.[0]?.id || 0) || undefined
  const reportRunId = runs.data?.find((row) => row.payroll_period_id === periodId && ['approved', 'posted', 'payment_prepared', 'partially_settled', 'settled', 'payslips_released', 'paid'].includes(row.status))?.id
  const [reportKind, setReportKind] = useState<'nd7a' | 'nd7b' | 'nd8' | 'tt11'>('nd8')
  const slips = usePayrollRunPayslips(runId, kind === 'slips' && Boolean(flags.view_salary))
  const report = usePayrollReport(reportRunId, reportKind, kind === 'reports' && view === 'statutory' && Boolean(flags.export), periodId)
  const glTotals = usePayrollPeriodGLTotals(periodId, kind === 'reports' && view === 'statutory' && Boolean(flags.export))
  const register = usePayrollSalaryRegister(runId, kind === 'reports' && view === 'salary-register' && Boolean(flags.export))
  const remittance = usePayrollBankRemittance(runId, kind === 'reports' && view === 'bank-remittance' && Boolean(flags.export))
  const registerGroups = Object.entries((register.data || []).reduce<Record<string, NonNullable<typeof register.data>>>((groups, row) => { const key = row.department || 'Бусад'; (groups[key] ||= []).push(row); return groups }, {})).sort(([a], [b]) => a.localeCompare(b, 'mn'))
  const download = (format: 'csv' | 'xlsx' | 'pdf') => {
    if (!reportRunId) return
    downloadPayrollReport(reportRunId, reportKind, format, periodId).catch((error: any) => toast.error(error?.response?.data?.detail?.code || 'Тайлан татаж чадсангүй'))
  }
  return <PayrollShell><section className="payroll-v2-section"><h1>{kind === 'slips' ? 'Цалингийн хуудас' : 'Цалингийн тайлан'}</h1>{kind === 'slips' ? <label>Бодолт<select value={runId || ''} onChange={(event) => setParams({ run: event.target.value })}><option value="">Сонгох</option>{runs.data?.map((row) => <option key={row.id} value={row.id}>{row.run_number} · {payrollDocumentStatusLabel(row.status)}</option>)}</select></label> : <label>Payroll Period<select value={periodId || ''} onChange={(event) => setParams({ period: event.target.value, view })}><option value="">Үе сонгох</option>{periods.data?.map((period) => <option key={period.id} value={period.id}>{period.code} · {period.name}</option>)}</select></label>}
    {kind === 'slips' ? flags.view_salary ? <div className="payroll-v2-table-wrap"><table className="payroll-v2-table"><thead><tr><th>Ажилтан</th><th>Нийт цалин</th><th>НДШ</th><th>ХХОАТ</th><th>Олгох дүн</th></tr></thead><tbody>{slips.data?.map((row) => <tr key={row.id}><td>#{row.employee_id}</td><td>{formatPayrollMoney(row.gross)}</td><td>{formatPayrollMoney(row.employee_shi)}</td><td>{formatPayrollMoney(row.pit)}</td><td>{formatPayrollMoney(row.net_pay)}</td></tr>)}</tbody></table>{!slips.data?.length && <p>Энэ бодолтод цалингийн хуудас алга.</p>}</div> : <p role="alert">Цалингийн дэлгэрэнгүй харах эрх шаардлагатай.</p> : flags.export ? <>
      <label>Тайлангийн төрөл<select value={view} onChange={(event) => setParams({ ...(periodId ? { period: String(periodId) } : {}), view: event.target.value })}><option value="statutory">НДШ ба татвар</option><option value="salary-register">Цалингийн бүртгэл</option><option value="bank-remittance">Банкны шилжүүлэг</option></select></label>
      {view === 'salary-register' ? <><p aria-live="polite">{register.isLoading ? 'Бүртгэл ачаалж байна…' : register.isError ? 'Бүртгэлийг ачаалж чадсангүй.' : `${register.data?.length || 0} мөр`}</p><div className="payroll-v2-table-wrap payroll-v2-register-wrap"><table className="payroll-v2-table payroll-v2-register"><thead><tr><th>Алба</th><th>Ажилтан</th><th>Нийт цалин</th><th>Татвар ногдох орлого</th><th>Ажилтны НДШ</th><th>ХХОАТ</th><th>Хөнгөлөлт</th><th>Урьдчилгаа</th><th>Олгох дүн</th><th>Төлөв</th><th></th></tr></thead>{registerGroups.map(([department, rows]) => <tbody key={department}><tr className="payroll-v2-register-group"><th colSpan={11}>{department}</th></tr>{rows.map((row) => <tr key={row.salary_slip_id}><td className="payroll-v2-register-sticky payroll-v2-register-dept">{row.department || 'Бусад'}</td><td className="payroll-v2-register-sticky payroll-v2-register-employee">{row.employee_name || `#${row.employee_id}`}<small>{row.job_title || `#${row.employee_id}`}</small></td><td>{formatPayrollMoney(row.gross)}</td><td>{formatPayrollMoney(row.taxable_income)}</td><td>{formatPayrollMoney(row.employee_shi)}</td><td>{formatPayrollMoney(row.pit)}</td><td>{formatPayrollMoney(row.pit_relief)}</td><td>{formatPayrollMoney(row.advance_offset)}</td><td>{formatPayrollMoney(row.net_pay)}</td><td>{payrollDocumentStatusLabel(row.status)}</td><td><details><summary>Дэлгэрэнгүй</summary><dl>{row.lines.map((line) => <div key={`${line.code}-${line.kind}`}><dt>{line.label}</dt><dd>{formatPayrollMoney(line.amount)}</dd></div>)}<div><dt>Татварын суурь</dt><dd>{formatPayrollMoney(row.taxable_income)}</dd></div><div><dt>Хөнгөлөлт</dt><dd>{formatPayrollMoney(row.pit_relief)}</dd></div></dl></details></td></tr>)}<tr className="payroll-v2-register-subtotal"><th colSpan={2}>{department} дүн</th><td>{formatPayrollMoney(String(rows.reduce((sum, row) => sum + Number(row.gross), 0)))}</td><td colSpan={5}></td><td>{formatPayrollMoney(String(rows.reduce((sum, row) => sum + Number(row.net_pay), 0)))}</td><td colSpan={2}></td></tr></tbody>)}</table></div><button className="payroll-v2-button secondary" disabled={!runId} onClick={() => downloadPayrollSalaryRegister(runId, 'csv').catch(() => toast.error('Цалингийн бүртгэл татаж чадсангүй'))}>CSV татах</button></> : null}
      {view === 'bank-remittance' ? <><p aria-live="polite">{remittance.isLoading ? 'Шилжүүлэг ачаалж байна…' : remittance.isError ? 'Шилжүүлгийг ачаалж чадсангүй.' : `${remittance.data?.length || 0} мөр`}</p><div className="payroll-v2-table-wrap"><table className="payroll-v2-table"><thead><tr><th>Ажилтан</th><th>Банк</th><th>Дансны төгсгөл</th><th>Дүн</th><th>Төлөв</th></tr></thead><tbody>{remittance.data?.map((row) => <tr key={row.salary_slip_id}><td>#{row.employee_id}</td><td>{row.bank_code || '—'}</td><td>{row.account_last4 || '—'}</td><td>{formatPayrollMoney(row.amount)}</td><td>{payrollDocumentStatusLabel(row.payment_status)}</td></tr>)}</tbody></table></div></> : null}
      {view === 'statutory' ? <><label>Тайлан<select value={reportKind} onChange={(event) => setReportKind(event.target.value as typeof reportKind)}><option value="nd7a">НД-7А</option><option value="nd7b">НД-7Б</option><option value="nd8">НД-8</option><option value="tt11">ТТ-11</option></select></label><p aria-live="polite">{report.error ? 'Тайлан үүссэнгүй. Бодолтын төлөв болон layout-ийг шалгана уу.' : report.isLoading ? 'Тайлан ачаалж байна…' : report.data ? 'Тайлан бэлэн.' : 'Payroll Period сонгоно уу.'}</p>{glTotals.data && <><div className="payroll-v2-run-overview"><article><span>GL · Salary Expense</span><strong>{formatPayrollMoney(glTotals.data.total_salary_expense)}</strong></article><article><span>GL · Employee NDSH</span><strong>{formatPayrollMoney(glTotals.data.total_employee_ndsh)}</strong></article><article><span>GL · Employer NDSH</span><strong>{formatPayrollMoney(glTotals.data.total_employer_ndsh)}</strong></article><article><span>GL · PIT withheld</span><strong>{formatPayrollMoney(glTotals.data.total_pit_withheld)}</strong></article></div>{!glTotals.data.classified && <p role="alert">{glTotals.data.unclassified_lines} historic GL line(s) could not be classified; period totals need review.</p>}</>}{report.data?.gl_reconciliation && !report.data.gl_reconciliation.matched && <section className="payroll-v2-issues" role="status"><h3>GL and payslip totals differ</h3><p>Review the differences before filing or exporting.</p><ul>{Object.entries(report.data.gl_reconciliation.differences).map(([key, amount]) => <li key={key}>{key}: {formatPayrollMoney(String(amount))}</li>)}</ul></section>}<div className="payroll-v2-action-row"><button className="payroll-v2-button secondary" disabled={!reportRunId || !report.data} onClick={() => download('csv')}>CSV</button><button className="payroll-v2-button secondary" disabled={!reportRunId || !report.data} onClick={() => download('xlsx')}>XLSX</button><button className="payroll-v2-button secondary" disabled={!reportRunId || !report.data} onClick={() => download('pdf')}>PDF</button></div></> : null}
    </> : <p role="alert">Тайлан гаргах эрх шаардлагатай.</p>}
  </section></PayrollShell>
}
