import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  mn: { translation: {
    'nav.today': 'Өнөөдөр', 'nav.worktime': 'Ажлын цаг', 'nav.hr': 'Хүний нөөц', 'nav.projects': 'Төслүүд', 'nav.tasks': 'Даалгавар', 'nav.calendar': 'Календарь', 'nav.reports': 'Тайлан',
    'nav.capacity': 'Багийн ачаалал', 'nav.okrs': 'Зорилго', 'nav.plans': 'Төлөвлөгөө', 'nav.contracts': 'Гэрээ', 'nav.analytics': 'Үзүүлэлт', 'nav.settings': 'Тохиргоо', 'nav.companyFiles': 'Компаний файлууд', 'nav.chat': 'Чат',
    'analytics.workHours.eyebrow': 'АЖЛЫН ЦАГИЙН ТАРХАЛТ', 'analytics.workHours.title': 'Ажлын цагийн бүтэц', 'analytics.workHours.subtitle': 'Remote болон оффисын хуваарилалт', 'analytics.workHours.categories.remote': 'Remote', 'analytics.workHours.categories.office': 'Оффис', 'analytics.workHours.totalLogged': 'Нийт бүртгэл', 'analytics.workHours.hoursUnit': 'ц', 'analytics.workHours.newTrend': 'Шинэ', 'analytics.workHours.pointsUnit': 'пп', 'analytics.workHours.ofTotal': 'нийтээс', 'analytics.workHours.legendLabel': 'Ажлын цагийн ангилал', 'analytics.workHours.chartLabel': 'Нийт {{total}} ажлын цагийн диаграмм', 'analytics.workHours.loading': 'Ачаалж байна', 'analytics.workHours.emptyTitle': 'Энэ хугацаанд ажилласан цаг бүртгэгдээгүй байна', 'analytics.workHours.emptyDescription': 'Өөр хугацаа сонгох эсвэл ажил эхлүүлсний дараа энд хуваарилалт харагдана.', 'analytics.workHours.errorTitle': 'Ажлын цагийн мэдээлэл ачаалсангүй', 'analytics.workHours.errorDescription': 'Аналитикийн мэдээллийг түр авах боломжгүй байна.', 'analytics.workHours.retry': 'Дахин оролдох', 'analytics.workHours.noCategories': 'Ангилал сонгоогүй', 'analytics.workHours.showAll': 'Бүгдийг харуулах',
    'action.search': 'Хайх', 'action.open': 'Нээх', 'action.logout': 'Гарах', 'erp.title': 'Бизнесийн үйл ажиллагаа', 'erp.subtitle': 'Байгууллагад ашиглах ажлын урсгалыг идэвхжүүлнэ үү.', 'erp.modules': 'ERP модулиуд', 'erp.visible': 'Ажлын талбарт харагдана', 'erp.hidden': 'Ажлын талбарт нуусан', 'erp.permissionNotice': 'Модулийн тохиргоо нь зөвхөн харагдацад нөлөөлнө. Эрх болон аудит тусдаа хамгаалагдана.', 'erp.noModules': 'Харагдах ERP модуль алга', 'erp.noModulesHelp': 'Администратор дээрх модулиудыг идэвхжүүлж ажлын талбарыг тохируулна.', 'erp.masterTitle': 'Контексттэй үндсэн өгөгдөл үүсгэх', 'erp.masterSubtitle': 'Батлагдсан хүсэлт нь аудитын мөртэй үйл ажиллагааны бүртгэл болно.', 'erp.submitRequest': 'Хүсэлт илгээх', 'erp.requestCreated': 'Үндсэн өгөгдлийн хүсэлт үүслээ', 'erp.draftCreated': 'Ноорог үүслээ', 'erp.requiredMaster': 'Шаардлагатай талбаруудыг бөглөнө үү', 'erp.moduleUpdated': 'ERP модулийн харагдац шинэчлэгдлээ', 'payroll.workspace': 'Цалин бодолт', 'payroll.entry': 'Payroll Entry', 'payroll.getEmployees': 'Ажилтан авах', 'payroll.createSlips': 'Salary Slip үүсгэх', 'payroll.submitSlips': 'Salary Slip илгээх', 'payroll.makeBankEntry': 'Банкны бичилт үүсгэх', 'payroll.salaryRegister': 'Цалингийн бүртгэл', 'payroll.bankRemittance': 'Банкны шилжүүлэг',
    'files.layout': 'Харагдац', 'files.listView': 'Жагсаалт харагдац', 'files.gridView': 'Торон харагдац', 'files.downloadFolder': 'Хавтас татах', 'files.archiving': 'ZIP архив бэлтгэж байна…', 'files.archiveReady': 'ZIP архив татаж эхэллээ', 'files.archiveError': 'Хавтас татаж чадсангүй',
    'files.title': 'Компаний файлууд', 'files.subtitle': 'Байгууллагын хавтас, файлуудыг нэг дороос ашиглах боломжтой.', 'files.newFolder': 'Шинэ хавтас', 'files.upload': 'Файл оруулах', 'files.root': 'Файлын сан', 'files.trash': 'Хогийн сав', 'files.back': 'Буцах', 'files.search': 'Файл, хавтас хайх…', 'files.sort': 'Эрэмбэлэх', 'files.sortName': 'Нэрээр', 'files.sortNewest': 'Шинээр', 'files.sortOldest': 'Хуучнаар', 'files.sortSize': 'Хэмжээгээр', 'files.loading': 'Файлын сан ачаалж байна…', 'files.loadError': 'Файлын санг ачаалж чадсангүй.', 'files.retry': 'Дахин оролдох', 'files.emptyTrash': 'Хогийн сав хоосон', 'files.noResults': 'Илэрц олдсонгүй', 'files.emptyFolder': 'Энэ хавтас хоосон', 'files.emptyTrashHelp': 'Устгасан файл, хавтас энд харагдана.', 'files.emptyHelp': 'Шинэ хавтас үүсгэх эсвэл файл оруулж эхлээрэй.', 'files.name': 'Нэр', 'files.size': 'Хэмжээ', 'files.updated': 'Шинэчилсэн', 'files.folder': 'Хавтас', 'files.file': 'Файл', 'files.download': 'татах', 'files.rename': 'нэр солих', 'files.move': 'зөөх', 'files.restore': 'сэргээх', 'files.deleteForever': 'бүрмөсөн устгах', 'files.create': 'Шинэ хавтас', 'files.destination': 'Очих хавтас', 'files.cancel': 'Болих', 'files.save': 'Хадгалах', 'files.close': 'Хаах', 'files.breadcrumbs': 'Файлын зам', 'files.uploading': 'Оруулж байна', 'files.processing': 'Аюулгүй байдлын шалгалт, хадгалалт хийгдэж байна…', 'files.cancelUpload': 'Цуцлах', 'files.downloadError': 'Файл татаж чадсангүй', 'files.confirmTrashFolder': 'Энэ хавтас болон доторх зүйлсийг хогийн сав руу зөөх үү?', 'files.confirmTrashFile': 'Энэ файлыг хогийн сав руу зөөх үү?', 'files.confirmPermanent': 'Энэ item болон доторх файлуудыг сэргээх боломжгүйгээр устгах уу?',
  } },
  en: { translation: {
    'nav.today': 'Today', 'nav.worktime': 'Worktime', 'nav.hr': 'HR', 'nav.projects': 'Projects', 'nav.tasks': 'Tasks', 'nav.calendar': 'Calendar', 'nav.reports': 'Reports',
    'nav.capacity': 'Team capacity', 'nav.okrs': 'Goals', 'nav.plans': 'Plans', 'nav.contracts': 'Contracts', 'nav.analytics': 'Analytics', 'nav.settings': 'Settings', 'nav.companyFiles': 'Company files', 'nav.chat': 'Chat',
    'analytics.workHours.eyebrow': 'WORK HOUR DISTRIBUTION', 'analytics.workHours.title': 'Work Hour Hierarchy', 'analytics.workHours.subtitle': 'Remote vs. Office distribution', 'analytics.workHours.categories.remote': 'Remote', 'analytics.workHours.categories.office': 'Office', 'analytics.workHours.totalLogged': 'Total Logged', 'analytics.workHours.hoursUnit': 'hrs', 'analytics.workHours.newTrend': 'New', 'analytics.workHours.pointsUnit': 'pp', 'analytics.workHours.ofTotal': 'of total', 'analytics.workHours.legendLabel': 'Work hour categories', 'analytics.workHours.chartLabel': 'Work hour chart totaling {{total}}', 'analytics.workHours.loading': 'Loading', 'analytics.workHours.emptyTitle': 'No work hours recorded for this period', 'analytics.workHours.emptyDescription': 'Choose another period or start a work session to see the distribution here.', 'analytics.workHours.errorTitle': 'Work hours could not be loaded', 'analytics.workHours.errorDescription': 'The analytics data is temporarily unavailable.', 'analytics.workHours.retry': 'Try again', 'analytics.workHours.noCategories': 'No categories selected', 'analytics.workHours.showAll': 'Show all',
    'action.search': 'Search', 'action.open': 'Open', 'action.logout': 'Log out', 'erp.title': 'Business operations', 'erp.subtitle': 'Enable only the workflows your organization uses.', 'erp.modules': 'ERP modules', 'erp.visible': 'Visible in workspace', 'erp.hidden': 'Hidden from workspace', 'erp.permissionNotice': 'Module switches affect visibility only; permissions and audit remain enforced.', 'erp.noModules': 'No ERP modules are visible', 'erp.noModulesHelp': 'An administrator can enable modules above to configure the workspace.', 'erp.masterTitle': 'Create contextual master data', 'erp.masterSubtitle': 'Approved requests become operational records with an audit trail.', 'erp.submitRequest': 'Submit request', 'erp.requestCreated': 'Master-data request created', 'erp.draftCreated': 'Draft created', 'erp.requiredMaster': 'Complete the required fields', 'erp.moduleUpdated': 'ERP module visibility updated', 'payroll.workspace': 'Payroll workspace', 'payroll.entry': 'Payroll Entry', 'payroll.getEmployees': 'Get Employees', 'payroll.createSlips': 'Create Salary Slips', 'payroll.submitSlips': 'Submit Salary Slips', 'payroll.makeBankEntry': 'Make Bank Entry', 'payroll.salaryRegister': 'Salary Register', 'payroll.bankRemittance': 'Bank Remittance',
    'files.layout': 'Layout', 'files.listView': 'List view', 'files.gridView': 'Grid view', 'files.downloadFolder': 'Download folder', 'files.archiving': 'Preparing ZIP archive…', 'files.archiveReady': 'ZIP download started', 'files.archiveError': 'Could not download folder',
    'files.title': 'Company files', 'files.subtitle': 'Browse your organization’s shared folders and files.', 'files.newFolder': 'New folder', 'files.upload': 'Upload file', 'files.root': 'File library', 'files.trash': 'Trash', 'files.back': 'Back', 'files.search': 'Search files and folders…', 'files.sort': 'Sort', 'files.sortName': 'Name', 'files.sortNewest': 'Newest', 'files.sortOldest': 'Oldest', 'files.sortSize': 'Size', 'files.loading': 'Loading file library…', 'files.loadError': 'Could not load the file library.', 'files.retry': 'Try again', 'files.emptyTrash': 'Trash is empty', 'files.noResults': 'No results found', 'files.emptyFolder': 'This folder is empty', 'files.emptyTrashHelp': 'Deleted files and folders will appear here.', 'files.emptyHelp': 'Create a folder or upload a file to get started.', 'files.name': 'Name', 'files.size': 'Size', 'files.updated': 'Updated', 'files.folder': 'Folder', 'files.file': 'File', 'files.download': 'download', 'files.rename': 'Rename', 'files.move': 'Move', 'files.restore': 'restore', 'files.deleteForever': 'delete permanently', 'files.create': 'New folder', 'files.destination': 'Destination folder', 'files.cancel': 'Cancel', 'files.save': 'Save', 'files.close': 'Close', 'files.breadcrumbs': 'File path', 'files.uploading': 'Uploading', 'files.processing': 'Scanning and saving file…', 'files.cancelUpload': 'Cancel upload', 'files.downloadError': 'Could not download the file', 'files.confirmTrashFolder': 'Move this folder and its contents to trash?', 'files.confirmTrashFile': 'Move this file to trash?', 'files.confirmPermanent': 'Permanently delete this item and all files inside it?',
  } },
  ru: { translation: {
    'nav.today': 'Сегодня', 'nav.worktime': 'Рабочее время', 'nav.hr': 'HR', 'nav.projects': 'Проекты', 'nav.tasks': 'Задачи', 'nav.calendar': 'Календарь', 'nav.reports': 'Отчёты',
    'nav.capacity': 'Загрузка команды', 'nav.okrs': 'Цели', 'nav.plans': 'Планы', 'nav.contracts': 'Договоры', 'nav.analytics': 'Аналитика', 'nav.settings': 'Настройки', 'nav.companyFiles': 'Файлы компании', 'nav.chat': 'Чат',
    'analytics.workHours.eyebrow': 'РАСПРЕДЕЛЕНИЕ РАБОЧИХ ЧАСОВ', 'analytics.workHours.title': 'Структура рабочих часов', 'analytics.workHours.subtitle': 'Распределение удалённой и офисной работы', 'analytics.workHours.categories.remote': 'Удалённо', 'analytics.workHours.categories.office': 'Офис', 'analytics.workHours.totalLogged': 'Всего записано', 'analytics.workHours.hoursUnit': 'ч', 'analytics.workHours.newTrend': 'Новое', 'analytics.workHours.pointsUnit': 'пп', 'analytics.workHours.ofTotal': 'от общего', 'analytics.workHours.legendLabel': 'Категории рабочих часов', 'analytics.workHours.chartLabel': 'Диаграмма рабочих часов, всего {{total}}', 'analytics.workHours.loading': 'Загрузка', 'analytics.workHours.emptyTitle': 'За этот период рабочие часы не записаны', 'analytics.workHours.emptyDescription': 'Выберите другой период или начните рабочую сессию, чтобы увидеть распределение.', 'analytics.workHours.errorTitle': 'Не удалось загрузить рабочие часы', 'analytics.workHours.errorDescription': 'Аналитические данные временно недоступны.', 'analytics.workHours.retry': 'Повторить', 'analytics.workHours.noCategories': 'Категории не выбраны', 'analytics.workHours.showAll': 'Показать все',
    'action.search': 'Поиск', 'action.open': 'Открыть', 'action.logout': 'Выйти', 'erp.title': 'Бизнес-операции', 'erp.subtitle': 'Включайте только рабочие процессы вашей организации.', 'erp.modules': 'Модули ERP', 'erp.visible': 'Видно в рабочем пространстве', 'erp.hidden': 'Скрыто в рабочем пространстве', 'erp.permissionNotice': 'Переключатели меняют только видимость; права и аудит сохраняются.', 'erp.noModules': 'Нет видимых модулей ERP', 'erp.noModulesHelp': 'Администратор может включить модули выше.', 'erp.masterTitle': 'Создать контекстные основные данные', 'erp.masterSubtitle': 'Одобренные запросы становятся операционными записями с аудитом.', 'erp.submitRequest': 'Отправить запрос', 'erp.requestCreated': 'Запрос основных данных создан', 'erp.draftCreated': 'Черновик создан', 'erp.requiredMaster': 'Заполните обязательные поля', 'erp.moduleUpdated': 'Видимость модуля ERP обновлена', 'payroll.workspace': 'Рабочее пространство расчёта зарплаты', 'payroll.entry': 'Payroll Entry', 'payroll.getEmployees': 'Получить сотрудников', 'payroll.createSlips': 'Создать Salary Slips', 'payroll.submitSlips': 'Отправить Salary Slips', 'payroll.makeBankEntry': 'Создать банковскую запись', 'payroll.salaryRegister': 'Реестр зарплаты', 'payroll.bankRemittance': 'Банковский перевод',
    'files.layout': 'Макет', 'files.listView': 'Список', 'files.gridView': 'Сетка', 'files.downloadFolder': 'Скачать папку', 'files.archiving': 'Подготовка ZIP-архива…', 'files.archiveReady': 'Загрузка ZIP началась', 'files.archiveError': 'Не удалось скачать папку',
    'files.title': 'Файлы компании', 'files.subtitle': 'Общие папки и файлы вашей организации.', 'files.newFolder': 'Новая папка', 'files.upload': 'Загрузить файл', 'files.root': 'Библиотека файлов', 'files.trash': 'Корзина', 'files.back': 'Назад', 'files.search': 'Поиск файлов и папок…', 'files.sort': 'Сортировка', 'files.sortName': 'По имени', 'files.sortNewest': 'Сначала новые', 'files.sortOldest': 'Сначала старые', 'files.sortSize': 'По размеру', 'files.loading': 'Загрузка библиотеки…', 'files.loadError': 'Не удалось загрузить библиотеку.', 'files.retry': 'Повторить', 'files.emptyTrash': 'Корзина пуста', 'files.noResults': 'Ничего не найдено', 'files.emptyFolder': 'Эта папка пуста', 'files.emptyTrashHelp': 'Удалённые файлы и папки появятся здесь.', 'files.emptyHelp': 'Создайте папку или загрузите файл.', 'files.name': 'Имя', 'files.size': 'Размер', 'files.updated': 'Изменено', 'files.folder': 'Папка', 'files.file': 'Файл', 'files.download': 'скачать', 'files.rename': 'переименовать', 'files.move': 'переместить', 'files.restore': 'восстановить', 'files.deleteForever': 'удалить навсегда', 'files.create': 'Новая папка', 'files.destination': 'Папка назначения', 'files.cancel': 'Отмена', 'files.save': 'Сохранить', 'files.close': 'Закрыть', 'files.breadcrumbs': 'Путь к файлу', 'files.uploading': 'Загрузка', 'files.processing': 'Проверка безопасности и сохранение файла…', 'files.cancelUpload': 'Отменить загрузку', 'files.downloadError': 'Не удалось скачать файл', 'files.confirmTrashFolder': 'Переместить папку и её содержимое в корзину?', 'files.confirmTrashFile': 'Переместить файл в корзину?', 'files.confirmPermanent': 'Удалить элемент и все файлы внутри без возможности восстановления?',
  } },
}

i18n.use(initReactI18next).init({ resources, lng: 'mn', fallbackLng: 'mn', interpolation: { escapeValue: false } })

export default i18n
