import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  mn: { translation: {
    'nav.today': 'Өнөөдөр', 'nav.projects': 'Төслүүд', 'nav.tasks': 'Даалгавар', 'nav.calendar': 'Календарь', 'nav.reports': 'Тайлан',
    'nav.capacity': 'Багийн ачаалал', 'nav.okrs': 'Зорилго', 'nav.plans': 'Төлөвлөгөө', 'nav.analytics': 'Үзүүлэлт', 'nav.settings': 'Тохиргоо', 'nav.companyFiles': 'Компаний файлууд',
    'action.search': 'Хайх', 'action.open': 'Нээх', 'action.logout': 'Гарах',
    'files.title': 'Компаний файлууд', 'files.subtitle': 'Байгууллагын хавтас, файлуудыг нэг дороос ашиглах боломжтой.', 'files.newFolder': 'Шинэ хавтас', 'files.upload': 'Файл оруулах', 'files.root': 'Файлын сан', 'files.trash': 'Хогийн сав', 'files.back': 'Буцах', 'files.search': 'Файл, хавтас хайх…', 'files.sort': 'Эрэмбэлэх', 'files.sortName': 'Нэрээр', 'files.sortNewest': 'Шинээр', 'files.sortOldest': 'Хуучнаар', 'files.sortSize': 'Хэмжээгээр', 'files.loading': 'Файлын сан ачаалж байна…', 'files.loadError': 'Файлын санг ачаалж чадсангүй.', 'files.retry': 'Дахин оролдох', 'files.emptyTrash': 'Хогийн сав хоосон', 'files.noResults': 'Илэрц олдсонгүй', 'files.emptyFolder': 'Энэ хавтас хоосон', 'files.emptyTrashHelp': 'Устгасан файл, хавтас энд харагдана.', 'files.emptyHelp': 'Шинэ хавтас үүсгэх эсвэл файл оруулж эхлээрэй.', 'files.name': 'Нэр', 'files.size': 'Хэмжээ', 'files.updated': 'Шинэчилсэн', 'files.folder': 'Хавтас', 'files.file': 'Файл', 'files.download': 'татах', 'files.rename': 'нэр солих', 'files.move': 'зөөх', 'files.restore': 'сэргээх', 'files.deleteForever': 'бүрмөсөн устгах', 'files.create': 'Шинэ хавтас', 'files.destination': 'Очих хавтас', 'files.cancel': 'Болих', 'files.save': 'Хадгалах', 'files.close': 'Хаах', 'files.breadcrumbs': 'Файлын зам', 'files.uploading': 'Оруулж байна', 'files.downloadError': 'Файл татаж чадсангүй', 'files.confirmTrashFolder': 'Энэ хавтас болон доторх зүйлсийг хогийн сав руу зөөх үү?', 'files.confirmTrashFile': 'Энэ файлыг хогийн сав руу зөөх үү?', 'files.confirmPermanent': 'Энэ зүйл болон доторх файлуудыг сэргээх боломжгүйгээр устгах уу?',
  } },
  en: { translation: {
    'nav.today': 'Today', 'nav.projects': 'Projects', 'nav.tasks': 'Tasks', 'nav.calendar': 'Calendar', 'nav.reports': 'Reports',
    'nav.capacity': 'Team capacity', 'nav.okrs': 'Goals', 'nav.plans': 'Plans', 'nav.analytics': 'Analytics', 'nav.settings': 'Settings', 'nav.companyFiles': 'Company files',
    'action.search': 'Search', 'action.open': 'Open', 'action.logout': 'Log out',
    'files.title': 'Company files', 'files.subtitle': 'Browse your organization’s shared folders and files.', 'files.newFolder': 'New folder', 'files.upload': 'Upload file', 'files.root': 'File library', 'files.trash': 'Trash', 'files.back': 'Back', 'files.search': 'Search files and folders…', 'files.sort': 'Sort', 'files.sortName': 'Name', 'files.sortNewest': 'Newest', 'files.sortOldest': 'Oldest', 'files.sortSize': 'Size', 'files.loading': 'Loading file library…', 'files.loadError': 'Could not load the file library.', 'files.retry': 'Try again', 'files.emptyTrash': 'Trash is empty', 'files.noResults': 'No results found', 'files.emptyFolder': 'This folder is empty', 'files.emptyTrashHelp': 'Deleted files and folders will appear here.', 'files.emptyHelp': 'Create a folder or upload a file to get started.', 'files.name': 'Name', 'files.size': 'Size', 'files.updated': 'Updated', 'files.folder': 'Folder', 'files.file': 'File', 'files.download': 'download', 'files.rename': 'Rename', 'files.move': 'Move', 'files.restore': 'restore', 'files.deleteForever': 'delete permanently', 'files.create': 'New folder', 'files.destination': 'Destination folder', 'files.cancel': 'Cancel', 'files.save': 'Save', 'files.close': 'Close', 'files.breadcrumbs': 'File path', 'files.uploading': 'Uploading', 'files.downloadError': 'Could not download the file', 'files.confirmTrashFolder': 'Move this folder and its contents to trash?', 'files.confirmTrashFile': 'Move this file to trash?', 'files.confirmPermanent': 'Permanently delete this item and all files inside it?',
  } },
  ru: { translation: {
    'nav.today': 'Сегодня', 'nav.projects': 'Проекты', 'nav.tasks': 'Задачи', 'nav.calendar': 'Календарь', 'nav.reports': 'Отчёты',
    'nav.capacity': 'Загрузка команды', 'nav.okrs': 'Цели', 'nav.plans': 'Планы', 'nav.analytics': 'Аналитика', 'nav.settings': 'Настройки', 'nav.companyFiles': 'Файлы компании',
    'action.search': 'Поиск', 'action.open': 'Открыть', 'action.logout': 'Выйти',
    'files.title': 'Файлы компании', 'files.subtitle': 'Общие папки и файлы вашей организации.', 'files.newFolder': 'Новая папка', 'files.upload': 'Загрузить файл', 'files.root': 'Библиотека файлов', 'files.trash': 'Корзина', 'files.back': 'Назад', 'files.search': 'Поиск файлов и папок…', 'files.sort': 'Сортировка', 'files.sortName': 'По имени', 'files.sortNewest': 'Сначала новые', 'files.sortOldest': 'Сначала старые', 'files.sortSize': 'По размеру', 'files.loading': 'Загрузка библиотеки…', 'files.loadError': 'Не удалось загрузить библиотеку.', 'files.retry': 'Повторить', 'files.emptyTrash': 'Корзина пуста', 'files.noResults': 'Ничего не найдено', 'files.emptyFolder': 'Эта папка пуста', 'files.emptyTrashHelp': 'Удалённые файлы и папки появятся здесь.', 'files.emptyHelp': 'Создайте папку или загрузите файл.', 'files.name': 'Имя', 'files.size': 'Размер', 'files.updated': 'Изменено', 'files.folder': 'Папка', 'files.file': 'Файл', 'files.download': 'скачать', 'files.rename': 'переименовать', 'files.move': 'переместить', 'files.restore': 'восстановить', 'files.deleteForever': 'удалить навсегда', 'files.create': 'Новая папка', 'files.destination': 'Папка назначения', 'files.cancel': 'Отмена', 'files.save': 'Сохранить', 'files.close': 'Закрыть', 'files.breadcrumbs': 'Путь к файлу', 'files.uploading': 'Загрузка', 'files.downloadError': 'Не удалось скачать файл', 'files.confirmTrashFolder': 'Переместить папку и её содержимое в корзину?', 'files.confirmTrashFile': 'Переместить файл в корзину?', 'files.confirmPermanent': 'Удалить элемент и все файлы внутри без возможности восстановления?',
  } },
}

i18n.use(initReactI18next).init({ resources, lng: 'mn', fallbackLng: 'mn', interpolation: { escapeValue: false } })

export default i18n
