#!/usr/bin/env bash
# Pull secrets from Azure Key Vault and reconstruct .env files.
# Naming in KV: <project>--<scope>--<KEY-WITH-HYPHENS>
# On disk: <KEY_WITH_UNDERSCORES>=<value>
#
# Usage:
#   ./scripts/kv-pull.sh                  # pull all scopes for this project
#   ./scripts/kv-pull.sh <scope>          # pull a single scope
#   ./scripts/kv-pull.sh --list           # list available scopes
#
# Requires: az CLI, logged in subscription, Key Vault Secrets User role on kv-bronxtc-dev.

set -euo pipefail

VAULT="kv-bronxtc-dev"
PROJECT="tracker-artur"

# scope|outfile pairs (one per line)
SCOPES_TABLE='backend|backend/.env'

list_scopes() {
  while IFS='|' read -r s f; do
    [[ -z "$s" ]] && continue
    echo "  $s -> $f"
  done <<< "$SCOPES_TABLE"
}

find_outfile() {
  while IFS='|' read -r s f; do
    [[ -z "$s" ]] && continue
    if [[ "$s" == "$1" ]]; then echo "$f"; return 0; fi
  done <<< "$SCOPES_TABLE"
  return 1
}

pull_scope() {
  local scope="$1"
  local outfile="$2"
  local prefix="${PROJECT}--${scope}--"
  echo "→ ${scope}  (→ ${outfile})"
  local names
  names=$(az keyvault secret list --vault-name "$VAULT" \
            --query "[?starts_with(name, '${prefix}')].name" -o tsv)
  if [[ -z "$names" ]]; then
    echo "  (no secrets found with prefix ${prefix})"
    return 0
  fi
  [[ -f "$outfile" ]] && cp "$outfile" "${outfile}.bak"
  mkdir -p "$(dirname "$outfile")"
  {
    echo "# Generated by kv-pull.sh from $VAULT on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source prefix: $prefix"
    while IFS= read -r name; do
      local key="${name#$prefix}"
      key="${key//-/_}"
      local val
      val=$(az keyvault secret show --vault-name "$VAULT" --name "$name" --query value -o tsv)
      if [[ "$val" =~ [[:space:]\#\"\'\\$] ]]; then
        val="${val//\"/\\\"}"
        printf '%s="%s"\n' "$key" "$val"
      else
        printf '%s=%s\n' "$key" "$val"
      fi
    done <<< "$names"
  } > "$outfile"
  echo "  ✓ wrote $(grep -c '^[A-Z]' "$outfile") variables to $outfile"
}

case "${1:-}" in
  --list)
    echo "Available scopes for ${PROJECT}:"
    list_scopes
    ;;
  "")
    while IFS='|' read -r s f; do
      [[ -z "$s" ]] && continue
      pull_scope "$s" "$f"
    done <<< "$SCOPES_TABLE"
    ;;
  *)
    outfile=$(find_outfile "$1") || { echo "Unknown scope: $1"; echo "Use --list to see available scopes."; exit 1; }
    pull_scope "$1" "$outfile"
    ;;
esac
